// Inhalt DE: App-Seite /de/ und Ratgeber /de/ratgeber/.
// Dieselben Werte wie in der deutschen App-Version. Sie-Form.

export default {
  lang: 'de',
  ogLocale: 'de_DE',
  currency: 'EUR',
  appName: 'Calm Parent',
  appPath: '/de/',
  guidePath: '/de/ratgeber/',
  ui: {
    navGuide: 'ratgeber',
    navApp: 'app',
    guideName: 'Ratgeber',
    cta: 'Jetzt bei Google Play',
    answer: 'Kurz gesagt',
    updated: 'Aktualisiert',
    date: '27. September 2026',
    basedOn: 'Grundlage',
    sources: 'Quellen',
    related: 'Weiterlesen',
    appSuffix: 'Ohne Werbung, 14 Tage Premium gratis.',
    articleDisclaimer: 'Dieser Artikel dient nur der Information und ersetzt keine ärztliche Beratung. Wenn Sie etwas beunruhigt, wenden Sie sich an einen Arzt. Im Notfall rufen Sie die 112 an.',
    footer: 'Calm Parent · ein Projekt von <a href="/" style="color:var(--accent-dim);text-decoration:none;">skudev</a> · 2026',
    privacy: 'datenschutz',
  },
  landing: {
    title: 'Calm Parent: Baby-Tagebuch für beide Eltern · Android',
    description: 'Mahlzeiten, Schlaf, Windeln und Fieber mit einem Tipp. Ein Premium für beide Eltern, Fieber-Richtwerte aus kinderärztlichen Leitlinien und ein PDF-Bericht für den Arzt. Ohne Werbung. Android-App bei Google Play.',
    eyebrow: '// App für Eltern · Android',
    h1: 'Baby-Tagebuch <em>für beide</em> Eltern.',
    lead: 'Mahlzeiten, Schlaf, Windeln und Fieber mit einem Tipp. Sie beide sehen dieselben Einträge, jeder auf dem eigenen Handy. Fieber-Richtwerte aus kinderärztlichen Leitlinien und ein PDF-Bericht für den Arztbesuch. Ohne Werbung.',
    guideButton: 'Ratgeber für Eltern',
    status: 'bei Google Play · Deutsch, Englisch, Polnisch, Französisch, Spanisch',
    storyLabel: '// warum diese App',
    story: 'Unser Kind bekam mitten in der Nacht Fieber. Ich suchte bei Google, was zu tun ist, und jede Seite sagte etwas anderes. <em>Ich wollte alles an einem Ort haben</em>: Messungen, gegebene Medikamente mit Uhrzeit und Richtwerte aus kinderärztlichen Leitlinien. So entstand Calm Parent.',
    storyAuthor: 'Mateusz, Papa und Entwickler der App',
    featuresLabel: '// was Sie bekommen',
    featuresTitle: 'Sechs Dinge, die mir in anderen Apps <em>gefehlt</em> haben.',
    features: [
      { emoji: '🍼', title: 'Eintrag mit einem Tipp', text: 'Stillen oder Fläschchen, Schlaf und Windeln. Mit dem Widget auf dem Startbildschirm erfassen Sie eine Mahlzeit, ohne die App zu öffnen.' },
      { emoji: '👨‍👩‍👧', title: 'Ein Premium für beide', text: 'Laden Sie Ihren Partner mit einem Code ein, und Sie sehen beide dieselben Einträge live. Einer zahlt, Premium gilt für beide.' },
      { emoji: '🌡️', title: 'Temperatur mit Verlauf', text: 'Messungen mit Uhrzeit und Verlaufskurve. Daneben Richtwerte aus kinderärztlichen Leitlinien, jederzeit zum Nachlesen.' },
      { emoji: '💊', title: 'Medikamente und Erinnerungen', text: 'Sie notieren, welches Medikament wann gegeben wurde. Die Erinnerung kommt auf beiden Handys an. Die App berechnet keine Dosierungen, prüfen Sie immer den Beipackzettel.' },
      { emoji: '📊', title: 'WHO-Kurven und PDF-Bericht', text: 'Gewicht, Größe und Kopfumfang auf WHO-Perzentilkurven. Einen PDF-Bericht für einen beliebigen Zeitraum nehmen Sie zum Kinderarzt mit.' },
      { emoji: '🔒', title: 'Ohne Werbung, Daten in der EU', text: 'Keine Werbung und kein Verkauf von Daten. Ihre Daten liegen auf Servern in der Europäischen Union, CSV-Export jederzeit.' },
    ],
    previewLabel: '// app-vorschau',
    previewTitle: 'Gemacht für <em>schnelle Einträge</em> mit einer Hand.',
    phones: [
      { img: 'dzis', label: '01 · Heute', title: 'Der ganze Tag auf einem Bildschirm', desc: 'Mahlzeiten, Schlaf, Windeln und die letzte Temperatur.', alt: 'Heute: Mahlzeiten, Schlaf, Windeln und die letzte Temperatur' },
      { img: 'karmienie', label: '02 · Mahlzeit', title: 'Mahlzeit in 2 Sekunden', desc: 'Brust, Flasche und Uhrzeit mit einem Tipp.', alt: 'Mahlzeit: linke Brust, rechte Brust, Flasche' },
      { img: 'wspolne-konto', label: '03 · Gemeinsames Konto', title: 'Ein Premium für beide', desc: 'Dieselben Einträge auf beiden Handys, live.', alt: 'Gemeinsames Konto: Einladungscode für den anderen Elternteil' },
    ],
    guidesLabel: '// ratgeber',
    ctaLabel: '// herunterladen',
    ctaTitle: '14 Tage Premium <em>gratis</em>, ohne Karte.',
    ctaLead: 'Nach 14 Tagen nutzen Sie die Basisversion weiter: Mahlzeiten, Schlaf, Temperatur und Medikamente erfassen bleibt kostenlos. Premium kaufen Sie nur, wenn Sie möchten.',
    disclaimer: 'Calm Parent ist kein Medizinprodukt. Die App stellt keine Diagnose, berechnet keine Dosierungen und ersetzt keinen Arzt. Im Notfall rufen Sie die 112 an.',
  },
  index: {
    title: 'Ratgeber für Eltern von Babys',
    description: 'Fieber, Mahlzeiten, Windeln, Schlaf und Warnzeichen beim Baby. Kurz und klar, nach kinderärztlichen Leitlinien.',
    eyebrow: '// Ratgeber für Eltern',
    h1: 'Kurz und klar, <em>nach kinderärztlichen</em> Leitlinien.',
    lead: 'Antworten auf die Fragen, die Eltern von Babys am häufigsten stellen, oft mitten in der Nacht. Jeder Artikel nennt seine Quellen.',
    disclaimer: 'Dieser Ratgeber dient nur der Information und ersetzt keine ärztliche Beratung. Im Notfall rufen Sie die 112 an.',
  },
  articles: [
    {
      id: 'fever',
      slug: 'fieber-baby-wann-zum-arzt',
      emoji: '🌡️',
      title: 'Fieber beim Baby: wann zum Arzt?',
      metaTitle: 'Fieber beim Baby: wann zum Arzt? Grenzwerte nach Alter',
      description: 'Ab welcher Temperatur muss ein Baby zum Arzt? Fieber-Grenzwerte nach Alter des Kindes, nach den Leitlinien der American Academy of Pediatrics.',
      teaser: 'Temperatur-Grenzwerte nach Alter.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'Bei einem Baby unter 3 Monaten ist jede Temperatur ab 38,0°C ein Grund für einen dringenden Arztbesuch, auch nachts. Von 3 bis 6 Monaten kontaktieren Sie ab 38,0°C den Kinderarzt. Bei älteren Kindern liegt die Grenze bei 39,0°C, und ab 40,5°C braucht jedes Kind dringend ärztliche Hilfe.',
      blocks: [
        { h2: 'Fieber-Grenzwerte nach Alter' },
        { table: {
          head: ['Alter des Kindes', 'Temperatur', 'Was tun'],
          rows: [
            ['Unter 3 Monaten', 'ab 38,0°C', 'Sofort zum Arzt, auch nachts', true],
            ['3 bis 6 Monate', 'ab 38,0°C', 'Kinderarzt kontaktieren'],
            ['Über 6 Monate', '38,5 bis 39,0°C', 'Hohes Fieber. Ein fiebersenkendes Mittel kann das Wohlbefinden verbessern, Dosierung laut Beipackzettel'],
            ['Über 6 Monate', 'ab 39,0°C', 'Kinderarzt kontaktieren'],
            ['In jedem Alter', 'ab 40,5°C', 'Dringend ärztliche Hilfe', true],
          ],
        } },
        { h2: 'Warum ist die Grenze bei den Jüngsten niedriger?' },
        { p: 'In den ersten 3 Lebensmonaten ist das Immunsystem noch unreif, und Fieber kann das einzige Zeichen einer ernsten Infektion sein. Deshalb empfehlen die Leitlinien eine dringende ärztliche Untersuchung, auch wenn das Baby sonst gut aussieht.' },
        { h2: 'Fieber länger als 3 Tage' },
        { p: 'Wenn ein Kind über 6 Monaten länger als 72 Stunden Fieber hat, kontaktieren Sie den Kinderarzt, auch wenn es ihm einigermaßen gut geht.' },
        { callout: { title: 'Nicht nur aufs Thermometer schauen', text: 'Apathie, Schwierigkeiten beim Wecken, Atemnot, Krampfanfälle oder Flecken, die auf Druck nicht verblassen, brauchen unabhängig von der Temperatur dringend Hilfe. Die ganze Liste: <a href="/de/ratgeber/warnzeichen-beim-baby/">Warnzeichen beim Baby</a>.' } },
        { h2: 'Messungen mit Uhrzeit notieren' },
        { p: 'Der Arzt fragt, seit wann das Fieber besteht, wie hoch es war und wann ein Medikament gegeben wurde. Wenn Sie Messungen mit Uhrzeit notieren, fällt die Antwort leichter, und Sie sehen, ob die Temperatur steigt oder sinkt.' },
      ],
      sources: [
        'American Academy of Pediatrics, Clinical Practice Guideline: Evaluation and Management of Well-Appearing Febrile Infants 8 to 60 Days Old (2021)',
        'American Academy of Pediatrics, HealthyChildren.org: Fever',
      ],
      app: 'Temperaturmessungen mit Verlaufskurve, gegebene Medikamente mit Uhrzeit und diese Grenzwerte an einem Ort, auch auf dem Handy des anderen Elternteils.',
      related: ['warning', 'diapers'],
    },
    {
      id: 'warning',
      slug: 'warnzeichen-beim-baby',
      emoji: '🚨',
      title: 'Warnzeichen beim Baby: wann nicht bis morgen warten',
      metaTitle: 'Warnzeichen beim Baby und Kind: wann in die Notaufnahme',
      description: 'Bei welchen Symptomen sollten Sie mit Ihrem Baby in die Notaufnahme oder die 112 rufen, und wann reicht der Kinderarzt? Nach den Leitlinien der American Academy of Pediatrics.',
      teaser: 'Wann in die Notaufnahme oder die 112 rufen.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'Warten Sie nicht bis morgen, wenn ein Baby unter 3 Monaten Fieber ab 38°C hat, wenn das Kind apathisch und schwer zu wecken ist, Atemnot oder bläuliche Lippen hat, einen Krampfanfall, einen steifen Nacken oder Flecken, die auf Druck nicht verblassen. Dann braucht es dringend Hilfe: Notaufnahme oder 112.',
      blocks: [
        { h2: 'Dringend: Notaufnahme oder 112' },
        { ol: [
          '<strong>Fieber ab 38°C bei einem Baby unter 3 Monaten</strong>, auch ohne andere Symptome.',
          '<strong>Temperatur ab 40,5°C</strong> in jedem Alter.',
          '<strong>Apathie, schwer zu wecken, keine Reaktion</strong> auf Stimme und Berührung.',
          '<strong>Atemnot</strong>, pfeifende Atmung, bläuliche Lippen.',
          '<strong>Krampfanfall, steifer Nacken</strong> oder <strong>Flecken, die auf Druck nicht verblassen</strong>.',
        ] },
        { h2: 'Wie prüfe ich, ob Flecken verblassen?' },
        { p: 'Drücken Sie ein durchsichtiges Glas fest auf den Ausschlag. Wenn die Flecken durch das Glas deutlich sichtbar bleiben, warten Sie nicht: Das braucht dringend Hilfe.' },
        { h2: 'Kinderarzt kontaktieren' },
        { ul: [
          '<strong>Zeichen von Austrocknung:</strong> Windel über 6 Stunden trocken, Weinen ohne Tränen, eingesunkene Fontanelle.',
          '<strong>Anhaltendes Erbrechen oder Durchfall</strong> länger als einen Tag bei einem Säugling.',
          '<strong>Fieber länger als 72 Stunden</strong> bei einem Kind über 6 Monaten.',
        ] },
        { callout: { title: 'Nummern', text: '<strong>112</strong> ist die Notrufnummer in ganz Europa. Außerhalb der Praxiszeiten hilft bei weniger dringenden Fragen der ärztliche Bereitschaftsdienst: <strong>116 117</strong>.' } },
        { p: 'Im Zweifel lieber einmal zu viel nachsehen lassen. Die Fieber-Grenzwerte nach Alter finden Sie im Artikel <a href="/de/ratgeber/fieber-baby-wann-zum-arzt/">Fieber beim Baby: wann zum Arzt</a>.' },
      ],
      sources: [
        'American Academy of Pediatrics',
        'Mayo Clinic',
      ],
      app: 'Die Liste der Warnzeichen und die Notrufnummer haben Sie in der App immer griffbereit, zusammen mit dem Verlauf der Messungen für den Arzt.',
      related: ['fever', 'diapers'],
    },
    {
      id: 'feeding',
      slug: 'wie-oft-trinkt-ein-baby',
      emoji: '🍼',
      title: 'Wie oft am Tag trinkt ein Baby?',
      metaTitle: 'Wie oft trinkt ein Baby? Mahlzeiten pro Tag nach Alter',
      description: 'Wie viele Mahlzeiten am Tag sind bei einem Neugeborenen, einem 3 Monate alten Baby und einem Einjährigen üblich? Bereiche nach American Academy of Pediatrics, WHO und ESPGHAN.',
      teaser: 'Übliche Zahl der Mahlzeiten vom Neugeborenen bis zum ersten Geburtstag.',
      basedOn: 'American Academy of Pediatrics, WHO, ESPGHAN',
      answer: 'Ein Neugeborenes trinkt im ersten Monat meist 8 bis 12 Mal am Tag, also etwa alle 2 bis 3 Stunden. Mit dem Alter werden es weniger: mit 4 bis 6 Monaten meist 5 bis 7, am Ende des ersten Jahres 4 bis 6 Mahlzeiten am Tag.',
      blocks: [
        { h2: 'Milchmahlzeiten pro Tag' },
        { table: {
          head: ['Alter des Kindes', 'Mahlzeiten pro Tag'],
          rows: [
            ['0 bis 1 Monat', '8 bis 12'],
            ['2 bis 3 Monate', '7 bis 9'],
            ['4 bis 6 Monate', '5 bis 7'],
            ['7 bis 12 Monate', '4 bis 6'],
            ['1 bis 2 Jahre', '3 bis 5'],
          ],
        } },
        { p: 'Gezählt werden Milchmahlzeiten (Brust und Flasche), ohne Beikost.' },
        { h2: 'Bereiche, keine Norm' },
        { p: 'Füttern nach Bedarf ist laut American Academy of Pediatrics und WHO der Standard. Die Zahl der Mahlzeiten schwankt von Tag zu Tag, zum Beispiel bei Wachstumsschüben. Wichtiger als die Zahl ist, ob Ihr Baby zunimmt und die Windeln nass sind. Wie Sie das prüfen: <a href="/de/ratgeber/wie-viele-nasse-windeln/">wie viele nasse Windeln ein gutes Zeichen sind</a>.' },
        { h2: 'Wann mit dem Kinderarzt sprechen' },
        { p: 'Wenn Sie Zweifel an der Gewichtszunahme haben oder Ihr Baby weniger nasse Windeln hat als sonst, sprechen Sie mit dem Kinderarzt oder einer Stillberaterin.' },
      ],
      sources: [
        'American Academy of Pediatrics, Breastfeeding and the Use of Human Milk (2022)',
        'WHO, Infant and young child feeding (2021)',
        'ESPGHAN, Complementary Feeding: A Position Paper (2017)',
      ],
      app: 'Stillen oder Fläschchen erfassen Sie mit einem Tipp. Die App zählt die Mahlzeiten des Tages und zeigt, wie lange die letzte her ist.',
      related: ['diapers', 'sleep'],
    },
    {
      id: 'diapers',
      slug: 'wie-viele-nasse-windeln',
      emoji: '💧',
      title: 'Wie viele nasse Windeln am Tag sind ein gutes Zeichen?',
      metaTitle: 'Wie viele nasse Windeln am Tag? Austrocknung beim Baby erkennen',
      description: 'Wie viele nasse Windeln sollte ein Baby am Tag haben, und woran erkennen Sie Austrocknung? Ein einfacher Weg zu prüfen, ob Ihr Baby genug trinkt.',
      teaser: 'Ein einfacher Weg zu prüfen, ob Ihr Baby genug trinkt.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'Ab etwa dem 5. Lebenstag hat ein Baby meist mindestens 6 nasse Windeln am Tag. Weniger nasse Windeln, eine Windel, die über 6 Stunden trocken bleibt, Weinen ohne Tränen oder eine eingesunkene Fontanelle können auf Austrocknung hindeuten und sind ein Grund, den Arzt zu kontaktieren.',
      blocks: [
        { h2: 'Die ersten Tage nach der Geburt' },
        { p: 'In den ersten Tagen gibt es weniger nasse Windeln, weil noch wenig Milch da ist. Ihre Zahl steigt von Tag zu Tag, und ab etwa dem 5. Tag sollten es mindestens 6 am Tag sein.' },
        { h2: 'Zeichen für Austrocknung' },
        { ul: [
          'Windel über 6 Stunden trocken',
          'Weinen ohne Tränen',
          'Eingesunkene Fontanelle',
          'Weniger als 6 nasse Windeln am Tag',
        ] },
        { callout: { title: 'Wann zum Arzt', text: 'Bei Zeichen von Austrocknung kontaktieren Sie den Arzt, besonders bei einem Säugling. Auch anhaltendes Erbrechen oder Durchfall länger als einen Tag ist bei einem Säugling ein Grund anzurufen, weil es schnell zur Austrocknung führt.' } },
        { h2: 'Windeln nachts zählen' },
        { p: 'Nach ein paar schlaflosen Nächten weiß man kaum noch, wie viele Windeln es seit dem Morgen waren. Notieren Sie jeden Wechsel sofort, dann sehen Sie mit einem Blick, ob es heute genug waren.' },
      ],
      sources: [
        'American Academy of Pediatrics',
      ],
      app: 'Nasse und volle Windeln erfassen Sie mit einem Tipp, und die Zahl des ganzen Tages sehen Sie direkt auf dem Startbildschirm.',
      related: ['feeding', 'warning'],
    },
    {
      id: 'sleep',
      slug: 'wie-viel-schlaf-braucht-ein-baby',
      emoji: '😴',
      title: 'Wie viel sollte ein Baby schlafen?',
      metaTitle: 'Wie viel Schlaf braucht ein Baby? Schlaf pro Tag nach Alter',
      description: 'Wie viele Stunden am Tag schläft ein Neugeborenes, ein 4 Monate altes Baby und ein Einjähriges? Schlafbereiche nach National Sleep Foundation und American Academy of Pediatrics.',
      teaser: 'Schlaf pro Tag nach Alter, mit Nickerchen.',
      basedOn: 'National Sleep Foundation, American Academy of Pediatrics',
      answer: 'Bis zum 3. Monat schläft ein Baby insgesamt 14 bis 17 Stunden am Tag, von 4 bis 11 Monaten 12 bis 15 Stunden und mit 1 bis 2 Jahren 11 bis 14 Stunden, Nickerchen eingeschlossen.',
      blocks: [
        { h2: 'Schlaf pro Tag nach Alter' },
        { table: {
          head: ['Alter des Kindes', 'Schlaf pro Tag'],
          rows: [
            ['0 bis 3 Monate', '14 bis 17 Stunden'],
            ['4 bis 11 Monate', '12 bis 15 Stunden'],
            ['1 bis 2 Jahre', '11 bis 14 Stunden'],
            ['3 bis 5 Jahre', '10 bis 13 Stunden'],
          ],
        } },
        { p: 'Die Bereiche gelten für den ganzen Tag, mit Nickerchen. Jedes Kind schläft anders, sie sind also ein Anhaltspunkt und keine Norm.' },
        { h2: 'Neugeborene wachen oft auf' },
        { p: 'Ein Neugeborenes schläft in kurzen Abschnitten und wacht alle 1 bis 3 Stunden auf, meist zum Trinken. Der Rhythmus von Tag und Nacht stellt sich meist in den ersten 2 Monaten ein. Helle Tage und dunkle, ruhige Nächte helfen.' },
        { h2: 'Schlechterer Schlaf um den 4. Monat' },
        { p: 'Um den 4. Monat wird der Schlaf oft für eine Weile schlechter. Das ist ein natürlicher Schritt der Gehirnentwicklung und kein Fehler der Eltern.' },
      ],
      sources: [
        'National Sleep Foundation, Sleep Time Duration Recommendations (2015)',
        'American Academy of Pediatrics, Recommended Amount of Sleep for Pediatric Populations (2016)',
      ],
      app: 'Schlafbeginn und Schlafende erfassen Sie mit einem Tipp, und die App addiert Schlaf und Nickerchen des ganzen Tages.',
      related: ['feeding', 'fever'],
    },
    // v2 (29.09.2026): Themen der zweiten Shorts-Reihe.
    {
      id: 'thermometer',
      published: '2026-09-29',
      slug: 'fieber-messen-beim-baby',
      emoji: '🌡️',
      title: 'Fieber messen beim Baby: wo und wie?',
      metaTitle: 'Fieber messen beim Baby: Po, Achsel, Ohr oder Stirn?',
      description: 'Wo Sie beim Baby Fieber messen, damit der Wert zuverlässig ist: im Po, unter der Achsel, im Ohr oder an der Stirn. Methoden nach Alter, nach der American Academy of Pediatrics.',
      teaser: 'Welche Methode in welchem Alter.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'Bei Babys unter 3 Monaten ist die Messung im Po (rektal) am genauesten. Unter der Achsel geht es am einfachsten, aber am ungenauesten, deshalb unsichere Werte anders nachmessen. Ein Schläfenthermometer (Stirn) eignet sich ab 3 Monaten, ein Ohrthermometer ab 6 Monaten.',
      blocks: [
        { h2: 'Messmethoden nach Alter' },
        { table: {
          head: ['Methode', 'Ab welchem Alter', 'Genauigkeit'],
          rows: [
            ['Im Po (rektal)', 'ab Geburt', 'Am genauesten, empfohlen unter 3 Monaten'],
            ['Stirn (Schläfenthermometer)', 'ab 3 Monaten', 'Gut, laut Anleitung des Thermometers'],
            ['Im Ohr', 'ab 6 Monaten', 'Gut, bei jüngeren Babys ungenau'],
            ['Unter der Achsel', 'jedes Alter', 'Am ungenauesten, gut zur ersten Kontrolle'],
          ],
        } },
        { h2: 'So messen Sie sicher im Po' },
        { ol: [
          'Nehmen Sie ein digitales Thermometer und cremen Sie die Spitze mit etwas Vaseline ein.',
          'Legen Sie Ihr Baby auf den Rücken mit angezogenen Beinen oder bäuchlings auf Ihren Schoß.',
          'Führen Sie die Spitze vorsichtig etwa 1,5 cm ein und halten Sie sie bis zum Signal.',
          'Waschen Sie das Thermometer danach mit Wasser und Seife und nutzen Sie es nicht mehr im Mund.',
        ] },
        { h2: 'Unter der Achsel ist der Wert niedriger' },
        { p: 'Unter der Achsel ist der Wert meist niedriger als im Po. Ist das Ergebnis grenzwertig oder wirkt Ihr Baby trotz niedrigem Wert krank, messen Sie noch einmal mit einer genaueren Methode.' },
        { callout: { title: 'Ab wann ist es Fieber?', text: 'Fieber beginnt bei 38,0 °C. Bei einem Baby unter 3 Monaten braucht jedes Fieber sofort ärztliche Hilfe. Grenzwerte für ältere Kinder: <a href="/de/ratgeber/fieber-baby-wann-zum-arzt/">Fieber beim Baby: wann zum Arzt</a>.' } },
      ],
      sources: [
        'American Academy of Pediatrics, How to Take a Child’s Temperature (healthychildren.org)',
      ],
      app: 'Messwerte speichern Sie mit Uhrzeit und Messmethode, und das Diagramm zeigt, ob die Temperatur steigt oder fällt.',
      related: ['fever', 'warning'],
    },
    {
      id: 'glass',
      published: '2026-09-29',
      slug: 'glastest-ausschlag',
      emoji: '🥛',
      title: 'Der Glastest: Ausschlag und Fieber beim Kind',
      metaTitle: 'Glastest bei Ausschlag: wann Sie die 112 rufen',
      description: 'So machen Sie den Glastest bei Ausschlag mit Fieber und das bedeutet das Ergebnis. Flecken, die unter dem Glas nicht verblassen, können auf eine Meningokokken-Infektion hinweisen.',
      teaser: 'Flecken, die unter dem Glas nicht verblassen.',
      basedOn: 'NHS, Meningitis Research Foundation',
      answer: 'Drücken Sie ein klares Glas auf den Ausschlag und schauen Sie hindurch. Verblassen die Flecken, beobachten Sie Ihr Kind und rufen bei Fieber den Kinderarzt an. Verblassen die Flecken NICHT, rufen Sie sofort die 112: Es kann eine Meningokokken-Infektion sein.',
      blocks: [
        { h2: 'So machen Sie den Glastest' },
        { ol: [
          'Nehmen Sie ein klares Glas mit glatter Wand.',
          'Drücken Sie die Glaswand fest auf den Ausschlag.',
          'Schauen Sie durch das Glas, ob die Flecken unter dem Druck verblassen.',
        ] },
        { table: {
          head: ['Ergebnis', 'Was Sie sehen', 'Was tun'],
          rows: [
            ['Flecken verblassen', 'verschwinden unter dem Glas', 'Kind beobachten. Bei Fieber den Kinderarzt anrufen.'],
            ['Flecken verblassen NICHT', 'durch das Glas sichtbar', 'Sofort die 112 rufen', true],
          ],
        } },
        { h2: 'Dunkle Haut' },
        { p: 'Auf dunkler Haut ist ein Ausschlag schwerer zu erkennen. Prüfen Sie hellere Stellen: Handflächen, Fußsohlen, die Innenseite der Lider und den Gaumen.' },
        { callout: { title: 'Der Test ist nicht alles', text: 'Am Anfang kann der Ausschlag noch verblassen. Wirkt Ihr Kind sehr krank, ist es schläfrig, hat kalte Hände und Füße oder verschlechtert sich schnell, rufen Sie die 112, egal was der Glastest zeigt. Alle Warnzeichen: <a href="/de/ratgeber/warnzeichen-beim-baby/">Warnzeichen beim Baby</a>.' } },
      ],
      sources: [
        'NHS, Meningitis: symptoms and the glass test (nhs.uk)',
        'Meningitis Research Foundation',
      ],
      app: 'Warnzeichen und die 112 haben Sie in der App immer griffbereit, zusammen mit dem Temperaturverlauf für den Arzt.',
      related: ['warning', 'fever'],
    },
    {
      id: 'teeth',
      published: '2026-09-29',
      slug: 'wann-kommen-die-ersten-zaehne',
      emoji: '🦷',
      title: 'Wann kommen die ersten Zähne?',
      metaTitle: 'Wann kommen die ersten Zähne? Reihenfolge der Milchzähne',
      description: 'In welchem Alter der erste Zahn kommt und in welcher Reihenfolge die Milchzähne durchbrechen. Tabelle nach der American Academy of Pediatric Dentistry.',
      teaser: 'Reihenfolge der Milchzähne in Monaten.',
      basedOn: 'American Academy of Pediatric Dentistry, American Academy of Pediatrics',
      answer: 'Meist kommen zuerst die unteren Schneidezähne, zwischen dem 6. und 10. Monat, dann die oberen Schneidezähne (8 bis 12 Monate) und die seitlichen. Jedes Kind hat sein eigenes Tempo. Ist mit 18 Monaten noch kein Zahn da, fragen Sie den Zahnarzt. Zahnen macht kein hohes Fieber.',
      blocks: [
        { h2: 'Milchzähne: typisches Alter' },
        { table: {
          head: ['Zahn', 'Alter (Monate)', 'Hinweis'],
          rows: [
            ['Unten vorne', '6-10', 'Meist zuerst'],
            ['Oben vorne', '8-12', ''],
            ['Oben seitlich', '9-13', ''],
            ['Unten seitlich', '10-16', ''],
            ['Erste Backenzähne', '13-19', ''],
            ['Eckzähne', '16-23', ''],
            ['Zweite Backenzähne', '23-33', 'Meist zuletzt'],
          ],
        } },
        { h2: 'Anzeichen fürs Zahnen' },
        { p: 'Sabbern, auf allem herumkauen, Unruhe und schlechterer Schlaf sind typisch. Ein gekühlter (nicht gefrorener) Beißring und eine Massage des Zahnfleischs mit sauberem Finger helfen.' },
        { callout: { title: 'Fieber ist kein Zahnen', text: 'Zahnen kann die Temperatur leicht erhöhen, macht aber kein Fieber ab 38 °C. Hat Ihr Baby Fieber, suchen Sie nach einer anderen Ursache und wenden Sie sich an einen Arzt. Grenzwerte nach Alter: <a href="/de/ratgeber/fieber-baby-wann-zum-arzt/">Fieber beim Baby</a>.' } },
        { h2: 'Erster Zahnarztbesuch' },
        { p: 'Den ersten Besuch beim Kinderzahnarzt vereinbaren Sie am besten, sobald der erste Zahn da ist, spätestens um den ersten Geburtstag.' },
      ],
      sources: [
        'American Academy of Pediatric Dentistry, Dental Growth and Development',
        'American Academy of Pediatrics, Teething (healthychildren.org)',
      ],
      app: 'Im Bereich Zähnchen markieren Sie jeden Zahn mit Datum, und das Diagramm zeigt den Vergleich mit typischen Bereichen.',
      related: ['fever', 'sleep'],
    },
    {
      id: 'croup',
      published: '2026-09-29',
      slug: 'bellender-husten-pseudokrupp',
      emoji: '🐕',
      title: 'Bellender Husten in der Nacht: Pseudokrupp',
      metaTitle: 'Bellender Husten beim Kind (Pseudokrupp): was tun und wann 112',
      description: 'Husten wie ein bellender Hund, Heiserkeit und Pfeifen beim Einatmen. So erkennen Sie Pseudokrupp, was Sie nachts tun und wann Sie die 112 rufen.',
      teaser: 'Was nachts hilft und wann Sie die 112 rufen.',
      basedOn: 'NHS, American Academy of Pediatrics',
      answer: 'Bellender Husten und Heiserkeit, meist nachts schlimmer, sind typisch für Pseudokrupp, eine Entzündung von Kehlkopf und Luftröhre. Beruhigen Sie Ihr Kind und halten Sie es aufrecht. Rufen Sie die 112 bei Pfeifen beim Einatmen in Ruhe, eingezogener Haut zwischen den Rippen, blauen Lippen oder wenn Ihr Kind sabbert und nicht schlucken kann.',
      blocks: [
        { h2: 'So erkennen Sie Pseudokrupp' },
        { ul: [
          '<strong>Husten wie ein bellender Hund</strong> oder eine Robbe.',
          '<strong>Heiserkeit</strong> und veränderte Stimme.',
          '<strong>Pfeifendes Geräusch beim Einatmen</strong>, oft beim Weinen.',
          'Die Beschwerden sind meist <strong>nachts schlimmer</strong> und dauern einige Tage.',
        ] },
        { h2: 'Was tun' },
        { p: 'Beruhigen Sie Ihr Kind und halten Sie es sitzend oder aufrecht: Weinen und Angst verstärken die Atemnot. Bei Fieber oder Schmerzen können Sie ein fiebersenkendes Mittel laut Beipackzettel geben. Rufen Sie den Kinderarzt an, besonders wenn die Beschwerden nicht nachlassen.' },
        { h2: 'Dringend: 112' },
        { ol: [
          '<strong>Pfeifen beim Einatmen auch in Ruhe</strong>, wenn Ihr Kind ruhig ist.',
          '<strong>Die Haut zieht sich ein</strong> zwischen den Rippen oder unter dem Brustbein.',
          '<strong>Blaue Lippen</strong> oder sehr blasse, graue Haut.',
          '<strong>Starker Speichelfluss</strong>, Schlucken geht nicht.',
          '<strong>Schläfrigkeit</strong>, Ihr Kind ist vom Atmen erschöpft.',
        ] },
        { callout: { title: 'Nachts schlimmer, morgens besser', text: 'Pseudokrupp wird oft nachts schlimmer und morgens besser. Gab es nachts Atemnot, wenden Sie sich an den Kinderarzt, auch wenn es Ihrem Kind morgens besser geht. Außerhalb der Praxiszeiten hilft der ärztliche Bereitschaftsdienst unter <strong>116117</strong>. Weitere Warnzeichen: <a href="/de/ratgeber/warnzeichen-beim-baby/">Warnzeichen beim Baby</a>.' } },
      ],
      sources: [
        'NHS, Croup (nhs.uk)',
        'American Academy of Pediatrics, Croup and Your Young Child (healthychildren.org)',
      ],
      app: 'Hustenepisoden erfassen Sie mit Tageszeit und Stärke, und die App warnt bei bellendem oder pfeifendem Husten.',
      related: ['warning', 'fever'],
    },
    {
      id: 'solids',
      published: '2026-09-29',
      slug: 'wann-mit-beikost-anfangen',
      emoji: '🥕',
      title: 'Wann mit der Beikost anfangen?',
      metaTitle: 'Wann mit Beikost anfangen? 4 Zeichen der Bereitschaft',
      description: 'Ab wann Ihr Baby Beikost bekommen kann, woran Sie die Bereitschaft erkennen und was Sie vermeiden sollten. Nach WHO, ESPGHAN und American Academy of Pediatrics.',
      teaser: 'Zeichen der Bereitschaft und was Sie meiden.',
      basedOn: 'WHO, ESPGHAN, American Academy of Pediatrics',
      answer: 'Meist um den 6. Monat, frühestens ab Beginn des 5. Monats. Ihr Baby ist bereit, wenn es mit Unterstützung sitzt, den Kopf sicher hält, sich fürs Essen interessiert und den Löffel nicht mehr mit der Zunge herausschiebt. Kein Honig vor dem 12. Monat.',
      blocks: [
        { h2: 'Zeichen der Bereitschaft' },
        { ol: [
          '<strong>Sitzt mit Unterstützung</strong>, ohne umzukippen.',
          '<strong>Hält den Kopf sicher.</strong>',
          '<strong>Interessiert sich fürs Essen</strong>, greift danach, öffnet den Mund.',
          '<strong>Schiebt den Löffel nicht mehr mit der Zunge heraus.</strong>',
        ] },
        { h2: 'So fangen Sie an' },
        { ul: [
          'Neue Lebensmittel <strong>einzeln, alle 3-4 Tage</strong> einführen: So erkennen Sie Allergien leichter.',
          'Muttermilch oder Säuglingsnahrung bleibt im ersten Jahr die Hauptnahrung.',
          'Bieten Sie weiche Stückchen oder Brei passend zu den Fähigkeiten Ihres Babys an.',
        ] },
        { h2: 'Was Sie meiden sollten' },
        { table: {
          head: ['Lebensmittel', 'Ab wann', 'Warum'],
          rows: [
            ['Honig', 'nach dem 12. Monat', 'Botulismus-Risiko', true],
            ['Ganze Nüsse', 'ab 5 Jahren', 'Erstickungsgefahr', true],
            ['Kuhmilch als Getränk', 'nach dem 12. Monat', 'Zu wenig Eisen'],
          ],
        } },
        { callout: { title: 'Allergene', text: 'Häufige Allergene wie Ei oder feines Erdnussmus müssen nicht hinausgezögert werden. Gibt es in der Familie Nahrungsmittelallergien, besprechen Sie das Vorgehen mit dem Kinderarzt.' } },
      ],
      sources: [
        'WHO, Complementary feeding',
        'ESPGHAN, Complementary Feeding: A Position Paper (2017)',
        'American Academy of Pediatrics, Starting Solid Foods (healthychildren.org)',
      ],
      app: 'Im Bereich Beikost markieren Sie, was Ihr Baby schon probiert hat und ob es eine Reaktion gab.',
      related: ['feeding', 'teeth'],
    },
  ],
}
