// Content EN: app page /en/ and guide /en/guide/.
// Same medical data as the app's English version (AAP thresholds, °F added).

export default {
  lang: 'en',
  ogLocale: 'en_US',
  currency: 'USD',
  appName: 'Calm Parent',
  appPath: '/en/',
  guidePath: '/en/guide/',
  ui: {
    navGuide: 'guide',
    navApp: 'app',
    guideName: 'Guide',
    cta: 'Get it on Google Play',
    answer: 'In short',
    updated: 'Updated',
    date: 'September 27, 2026',
    basedOn: 'Based on',
    sources: 'Sources',
    related: 'Read next',
    appSuffix: 'No ads, 14 days of Premium free.',
    articleDisclaimer: 'This article is for information only and does not replace medical advice. If something worries you, contact a doctor. In an emergency, call your local emergency number.',
    footer: 'Calm Parent · a <a href="/" style="color:var(--accent-dim);text-decoration:none;">skudev</a> project · 2026',
    privacy: 'privacy',
  },
  landing: {
    title: 'Calm Parent: baby tracker for both parents · Android',
    description: 'Feedings, sleep, diapers and fever with one tap. One Premium for both parents, temperature thresholds from pediatric guidelines and a PDF report for the doctor. No ads. Android app on Google Play.',
    eyebrow: '// App for parents · Android',
    h1: 'A baby tracker <em>for both</em> parents.',
    lead: 'Feedings, sleep, diapers and fever with one tap. You both see the same entries, each on your own phone. Temperature thresholds from pediatric guidelines and a PDF report for the doctor. No ads.',
    guideButton: 'Guide for parents',
    status: 'on Google Play · English, Polish, German, French, Spanish',
    storyLabel: '// why this app',
    story: 'Our child got a fever in the middle of the night. I searched Google for what to do, and every site said something different. <em>I wanted everything in one place</em>: readings, medicines given with the time and thresholds from pediatric guidelines. That is how Calm Parent was born.',
    storyAuthor: 'Mateusz, dad and creator of the app',
    featuresLabel: '// what you get',
    featuresTitle: 'Six things I was <em>missing</em> in other apps.',
    features: [
      { emoji: '🍼', title: 'One-tap logging', text: 'Breastfeeding or bottle, sleep and diapers. Log a feeding from the home screen widget without opening the app.' },
      { emoji: '👨‍👩‍👧', title: 'One Premium for both', text: 'Invite your partner with a code and you both see the same entries in real time. One of you pays, Premium works for both.' },
      { emoji: '🌡️', title: 'Temperature with a chart', text: 'Readings with the time and a trend chart. Next to them, reference thresholds from pediatric guidelines, to read any time.' },
      { emoji: '💊', title: 'Medicines and reminders', text: 'Log which medicine was given and when. Reminders reach both phones. The app does not calculate doses, always check the leaflet.' },
      { emoji: '📊', title: 'WHO charts and PDF report', text: 'Weight, length and head circumference on WHO percentile charts. Take a PDF report for any period to the pediatrician.' },
      { emoji: '🔒', title: 'No ads, data in the EU', text: 'No ads and no selling of data. Your data is stored on servers in the European Union, with CSV export any time.' },
    ],
    previewLabel: '// app preview',
    previewTitle: 'Built for <em>quick logging</em> with one hand.',
    phones: [
      { img: 'dzis', label: '01 · Today', title: 'The whole day on one screen', desc: 'Feedings, sleep, diapers and the latest temperature.', alt: 'Today screen: feedings, sleep, diapers and the latest temperature' },
      { img: 'karmienie', label: '02 · Feeding', title: 'A feeding in 2 seconds', desc: 'Breast, bottle and time with one tap.', alt: 'Feeding screen: left breast, right breast, bottle' },
      { img: 'wspolne-konto', label: '03 · Shared account', title: 'One Premium for both', desc: 'The same entries on both phones, in real time.', alt: 'Shared account: invite code for the other parent' },
    ],
    guidesLabel: '// guide',
    ctaLabel: '// download',
    ctaTitle: '14 days of Premium <em>free</em>, no card.',
    ctaLead: 'After 14 days you keep the basic version: logging feedings, sleep, temperature and medicines stays free. You only buy Premium if you want to.',
    disclaimer: 'Calm Parent is not a medical device. It does not diagnose, does not calculate medicine doses and does not replace a doctor. In an emergency, call your local emergency number.',
  },
  index: {
    title: 'Guide for parents of babies',
    description: 'Fever, feeding, diapers, sleep and warning signs in babies. Short and clear, based on pediatric guidelines.',
    eyebrow: '// Guide for parents',
    h1: 'Short and clear, <em>from pediatric</em> guidelines.',
    lead: 'Answers to the questions parents of babies ask most, often in the middle of the night. Every article lists its sources.',
    disclaimer: 'This guide is for information only and does not replace medical advice. In an emergency, call your local emergency number.',
  },
  articles: [
    {
      id: 'fever',
      slug: 'baby-fever-when-to-see-a-doctor',
      emoji: '🌡️',
      title: 'Baby fever: when to see a doctor?',
      metaTitle: 'Baby fever: when to see a doctor? Thresholds by age',
      description: 'At what temperature should you take a baby to the doctor? Fever thresholds by age, based on American Academy of Pediatrics guidelines.',
      teaser: 'Temperature thresholds by age.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'For a baby under 3 months, any temperature of 38.0°C (100.4°F) or higher needs urgent medical attention, even at night. From 3 to 6 months, call your pediatrician at 38.0°C. For older children the threshold for a call is 39.0°C (102.2°F), and at 40.5°C (105°F) any child needs urgent help.',
      blocks: [
        { h2: 'Fever thresholds by age' },
        { table: {
          head: ['Child’s age', 'Temperature', 'What to do'],
          rows: [
            ['Under 3 months', '≥ 38.0°C / 100.4°F', 'See a doctor urgently, even at night', true],
            ['3 to 6 months', '≥ 38.0°C / 100.4°F', 'Call your pediatrician'],
            ['Over 6 months', '38.5 to 39.0°C / 101.3 to 102.2°F', 'High fever. A fever reducer can make your child more comfortable, dose as per the leaflet'],
            ['Over 6 months', '≥ 39.0°C / 102.2°F', 'Call your pediatrician'],
            ['Any age', '≥ 40.5°C / 105°F', 'Urgent medical help', true],
          ],
        } },
        { h2: 'Why is the threshold lower for the youngest babies?' },
        { p: 'In the first 3 months, a baby’s immune system is still immature, and fever may be the only sign of a serious infection. That is why guidelines recommend urgent medical assessment even when the baby otherwise looks well.' },
        { h2: 'Fever lasting more than 3 days' },
        { p: 'If a child over 6 months has had a fever for more than 72 hours, call your pediatrician, even if the child seems fairly well.' },
        { callout: { title: 'Don’t just look at the thermometer', text: 'Lethargy, difficulty waking, trouble breathing, seizures or a rash that does not fade when pressed need urgent help regardless of the temperature. Full list: <a href="/en/guide/warning-signs-in-babies/">warning signs in babies</a>.' } },
        { h2: 'Log readings with the time' },
        { p: 'The doctor will ask how long the fever has lasted, how high it was and when medicine was given. If you log readings with the time, it is easier to answer and to see whether the temperature is rising or falling.' },
      ],
      sources: [
        'American Academy of Pediatrics, Clinical Practice Guideline: Evaluation and Management of Well-Appearing Febrile Infants 8 to 60 Days Old (2021)',
        'American Academy of Pediatrics, HealthyChildren.org: Fever',
      ],
      app: 'Temperature readings with a chart, medicines given with the time and these thresholds in one place, also on the other parent’s phone.',
      related: ['warning', 'diapers'],
    },
    {
      id: 'warning',
      slug: 'warning-signs-in-babies',
      emoji: '🚨',
      title: 'Warning signs in babies: when not to wait until morning',
      metaTitle: 'Warning signs in babies and children: when to go to the ER',
      description: 'Which symptoms in a baby or child mean you should go to the emergency room or call emergency services, and when a call to the pediatrician is enough. Based on AAP guidelines.',
      teaser: 'When to go to the ER or call emergency services.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'Don’t wait until morning if a baby under 3 months has a fever of 38°C (100.4°F) or more, or if a child is lethargic and hard to wake, has trouble breathing or bluish lips, has a seizure, a stiff neck or a rash that does not fade when pressed. Get urgent help: go to the emergency room or call your local emergency number.',
      blocks: [
        { h2: 'Urgent: ER or emergency number' },
        { ol: [
          '<strong>Fever of 38°C (100.4°F) or more in a baby under 3 months</strong>, even with no other symptoms.',
          '<strong>Temperature of 40.5°C (105°F) or more</strong> at any age.',
          '<strong>Lethargy, difficulty waking, not responding</strong> to voice or touch.',
          '<strong>Trouble breathing</strong>, wheezing, bluish lips.',
          '<strong>Seizures, a stiff neck</strong> or <strong>a rash that does not fade when pressed</strong>.',
        ] },
        { h2: 'How to check if a rash fades' },
        { p: 'Press the side of a clear glass firmly against the rash. If the spots are still clearly visible through the glass, don’t wait: this needs urgent help.' },
        { h2: 'Call your doctor' },
        { ul: [
          '<strong>Signs of dehydration:</strong> a dry diaper for more than 6 hours, crying without tears, a sunken soft spot on the head.',
          '<strong>Persistent vomiting or diarrhea</strong> lasting more than a day in a baby.',
          '<strong>Fever lasting more than 72 hours</strong> in a child over 6 months.',
        ] },
        { callout: { title: 'Emergency numbers', text: 'Use your local emergency number: <strong>112</strong> across the European Union, <strong>999</strong> in the UK, <strong>911</strong> in the US and Canada. In the UK, <strong>NHS 111</strong> helps with urgent problems that are not life threatening.' } },
        { p: 'In doubt? Better to check once too often. Temperature thresholds by age are in <a href="/en/guide/baby-fever-when-to-see-a-doctor/">baby fever: when to see a doctor</a>.' },
      ],
      sources: [
        'American Academy of Pediatrics',
        'Mayo Clinic',
      ],
      app: 'The list of warning signs and emergency info are always at hand in the app, together with the history of readings you can show the doctor.',
      related: ['fever', 'diapers'],
    },
    {
      id: 'feeding',
      slug: 'how-often-do-babies-eat',
      emoji: '🍼',
      title: 'How many times a day does a baby eat?',
      metaTitle: 'How often do babies eat? Feedings per day by age',
      description: 'How many feedings a day are typical for a newborn, a 3-month-old and a 1-year-old? Ranges from the American Academy of Pediatrics, WHO and ESPGHAN.',
      teaser: 'Typical number of feedings from newborn to one year.',
      basedOn: 'American Academy of Pediatrics, WHO, ESPGHAN',
      answer: 'In the first month, a newborn usually feeds 8 to 12 times a day, roughly every 2 to 3 hours. With age there are fewer feedings: usually 5 to 7 a day at 4 to 6 months, and 4 to 6 by the end of the first year.',
      blocks: [
        { h2: 'Milk feedings per day' },
        { table: {
          head: ['Child’s age', 'Feedings per day'],
          rows: [
            ['0 to 1 month', '8 to 12'],
            ['2 to 3 months', '7 to 9'],
            ['4 to 6 months', '5 to 7'],
            ['7 to 12 months', '4 to 6'],
            ['1 to 2 years', '3 to 5'],
          ],
        } },
        { p: 'We count milk feedings (breast and bottle), not solid meals.' },
        { h2: 'Ranges, not rules' },
        { p: 'Feeding on demand is the standard recommended by the American Academy of Pediatrics and the WHO. The number of feedings changes from day to day, for example during growth spurts. More important than the number is whether your baby gains weight and has wet diapers. How to check that: <a href="/en/guide/how-many-wet-diapers/">how many wet diapers are a good sign</a>.' },
        { h2: 'When to talk to your pediatrician' },
        { p: 'If you have doubts about weight gain, or your baby has fewer wet diapers than usual, talk to your pediatrician or a lactation consultant.' },
      ],
      sources: [
        'American Academy of Pediatrics, Breastfeeding and the Use of Human Milk (2022)',
        'WHO, Infant and young child feeding (2021)',
        'ESPGHAN, Complementary Feeding: A Position Paper (2017)',
      ],
      app: 'Log breastfeeding or a bottle with one tap. The app counts the day’s feedings and shows how long it has been since the last one.',
      related: ['diapers', 'sleep'],
    },
    {
      id: 'diapers',
      slug: 'how-many-wet-diapers',
      emoji: '💧',
      title: 'How many wet diapers a day is a good sign?',
      metaTitle: 'How many wet diapers should a baby have? Signs of dehydration',
      description: 'How many wet diapers a day should a baby have, and what are the signs of dehydration? A simple way to check your baby is getting enough.',
      teaser: 'A simple way to check your baby is not dehydrated.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'From about day 5 of life, a baby usually has at least 6 wet diapers (nappies) a day. Fewer wet diapers, a dry diaper for more than 6 hours, crying without tears or a sunken soft spot may mean dehydration and are a reason to contact a doctor.',
      blocks: [
        { h2: 'The first days after birth' },
        { p: 'In the first days there are fewer wet diapers because there is still little milk. The number grows day by day, and from about day 5 there should be at least 6 a day.' },
        { h2: 'Signs of dehydration' },
        { ul: [
          'A dry diaper for more than 6 hours',
          'Crying without tears',
          'A sunken soft spot (fontanelle) on the head',
          'Fewer than 6 wet diapers a day',
        ] },
        { callout: { title: 'When to see a doctor', text: 'With signs of dehydration, contact a doctor, especially with a young baby. Persistent vomiting or diarrhea lasting more than a day in a baby is also a reason to call, because it quickly leads to dehydration.' } },
        { h2: 'Counting diapers at night' },
        { p: 'After a few sleepless nights it is hard to remember how many diapers there were since morning. Log each change right away, then one glance tells you whether today was enough.' },
      ],
      sources: [
        'American Academy of Pediatrics',
      ],
      app: 'Log wet and dirty diapers with one tap and see the count for the whole day right on the home screen.',
      related: ['feeding', 'warning'],
    },
    {
      id: 'sleep',
      slug: 'how-much-should-a-baby-sleep',
      emoji: '😴',
      title: 'How much should a baby sleep?',
      metaTitle: 'How much should a baby sleep? Sleep per day by age',
      description: 'How many hours a day does a newborn, a 4-month-old and a 1-year-old sleep? Sleep ranges from the National Sleep Foundation and the American Academy of Pediatrics.',
      teaser: 'Sleep per day by age, naps included.',
      basedOn: 'National Sleep Foundation, American Academy of Pediatrics',
      answer: 'Up to 3 months, a baby sleeps 14 to 17 hours a day in total, from 4 to 11 months 12 to 15 hours, and at 1 to 2 years 11 to 14 hours, naps included.',
      blocks: [
        { h2: 'Sleep per day by age' },
        { table: {
          head: ['Child’s age', 'Sleep per day'],
          rows: [
            ['0 to 3 months', '14 to 17 hours'],
            ['4 to 11 months', '12 to 15 hours'],
            ['1 to 2 years', '11 to 14 hours'],
            ['3 to 5 years', '10 to 13 hours'],
          ],
        } },
        { p: 'These ranges cover the whole day, naps included. Every child sleeps differently, so treat them as a reference, not a rule.' },
        { h2: 'Newborns wake often' },
        { p: 'A newborn sleeps in short stretches and wakes every 1 to 3 hours, mostly to feed. The day and night rhythm usually settles during the first 2 months. Bright days and dark, quiet nights help.' },
        { h2: 'Worse sleep around 4 months' },
        { p: 'Around 4 months, sleep often gets worse for a while. It is a natural stage of brain development, not a parenting mistake.' },
      ],
      sources: [
        'National Sleep Foundation, Sleep Time Duration Recommendations (2015)',
        'American Academy of Pediatrics, Recommended Amount of Sleep for Pediatric Populations (2016)',
      ],
      app: 'Start and end sleep with one tap, and the app adds up sleep and naps for the whole day.',
      related: ['feeding', 'fever'],
    },
  ],
}
