// Contenido ES: página de la app /es/ y guía /es/guia/.
// Mismos valores que la versión española de la app. Tuteo.

export default {
  lang: 'es',
  ogLocale: 'es_ES',
  currency: 'EUR',
  appName: 'Calm Parent',
  appPath: '/es/',
  guidePath: '/es/guia/',
  ui: {
    navGuide: 'guía',
    navApp: 'app',
    guideName: 'Guía',
    cta: 'Disponible en Google Play',
    answer: 'En resumen',
    updated: 'Actualizado',
    date: '27 de septiembre de 2026',
    basedOn: 'Basado en',
    sources: 'Fuentes',
    related: 'Lee también',
    appSuffix: 'Sin anuncios, 14 días de Premium gratis.',
    articleDisclaimer: 'Este artículo es informativo y no sustituye el consejo médico. Si algo te preocupa, consulta con un médico. En caso de emergencia, llama al 112.',
    footer: 'Calm Parent · un proyecto de <a href="/" style="color:var(--accent-dim);text-decoration:none;">skudev</a> · 2026',
    privacy: 'privacidad',
  },
  landing: {
    title: 'Calm Parent: el diario del bebé para los dos padres · Android',
    description: 'Tomas, sueño, pañales y fiebre con un toque. Un Premium para los dos padres, umbrales de fiebre de las guías pediátricas e informe PDF para el médico. Sin anuncios. App Android en Google Play.',
    eyebrow: '// App para padres · Android',
    h1: 'El diario del bebé <em>para los dos</em> padres.',
    lead: 'Tomas, sueño, pañales y fiebre con un toque. Los dos veis los mismos registros, cada uno en su móvil. Umbrales de fiebre de las guías pediátricas e informe PDF para la consulta. Sin anuncios.',
    guideButton: 'Guía para padres',
    status: 'en Google Play · español, inglés, alemán, francés, polaco',
    storyLabel: '// por qué esta app',
    story: 'Nuestro hijo tuvo fiebre en plena noche. Busqué en Google qué hacer, y cada página decía una cosa distinta. <em>Quería tenerlo todo en un solo lugar</em>: las mediciones, los medicamentos con la hora y los umbrales de las guías pediátricas. Así nació Calm Parent.',
    storyAuthor: 'Mateusz, padre y creador de la app',
    featuresLabel: '// qué obtienes',
    featuresTitle: 'Seis cosas que <em>echaba de menos</em> en otras apps.',
    features: [
      { emoji: '🍼', title: 'Registro con un toque', text: 'Pecho o biberón, sueño y pañales. Con el widget de la pantalla de inicio anotas una toma sin abrir la app.' },
      { emoji: '👨‍👩‍👧', title: 'Un Premium para los dos', text: 'Invita a tu pareja con un código y los dos veis los mismos registros al momento. Paga uno, Premium funciona para los dos.' },
      { emoji: '🌡️', title: 'Temperatura con gráfico', text: 'Mediciones con la hora y gráfico de tendencia. Al lado, los umbrales de referencia de las guías pediátricas, para leer cuando quieras.' },
      { emoji: '💊', title: 'Medicamentos y recordatorios', text: 'Anotas qué medicamento se dio y a qué hora. El recordatorio llega a los dos móviles. La app no calcula dosis, consulta siempre el prospecto.' },
      { emoji: '📊', title: 'Curvas OMS e informe PDF', text: 'Peso, talla y perímetro cefálico en las curvas de percentiles de la OMS. Un informe PDF del periodo que elijas para llevar al pediatra.' },
      { emoji: '🔒', title: 'Sin anuncios, datos en la UE', text: 'Sin publicidad y sin venta de datos. Tus datos se guardan en servidores de la Unión Europea, con exportación a CSV cuando quieras.' },
    ],
    previewLabel: '// vista previa',
    previewTitle: 'Pensada para <em>anotar rápido</em> con una mano.',
    phones: [
      { img: 'dzis', label: '01 · Hoy', title: 'Todo el día en una pantalla', desc: 'Tomas, sueño, pañales y la última temperatura.', alt: 'Pantalla Hoy: tomas, sueño, pañales y la última temperatura' },
      { img: 'karmienie', label: '02 · Toma', title: 'Una toma en 2 segundos', desc: 'Pecho, biberón y hora con un toque.', alt: 'Pantalla de tomas: pecho izquierdo, pecho derecho, biberón' },
      { img: 'wspolne-konto', label: '03 · Cuenta compartida', title: 'Un Premium para los dos', desc: 'Los mismos registros en ambos móviles, al momento.', alt: 'Cuenta compartida: código de invitación para el otro progenitor' },
    ],
    guidesLabel: '// guía',
    ctaLabel: '// descargar',
    ctaTitle: '14 días de Premium <em>gratis</em>, sin tarjeta.',
    ctaLead: 'Después de 14 días sigues con la versión básica: registrar tomas, sueño, temperatura y medicamentos sigue siendo gratis. Solo compras Premium si quieres.',
    disclaimer: 'Calm Parent no es un dispositivo médico. No diagnostica, no calcula dosis y no sustituye a un médico. En caso de emergencia, llama al 112.',
  },
  index: {
    title: 'Guía para padres de bebés',
    description: 'Fiebre, tomas, pañales, sueño y señales de alarma en el bebé. Breve y claro, según las guías pediátricas.',
    eyebrow: '// Guía para padres',
    h1: 'Breve y claro, <em>según las guías</em> pediátricas.',
    lead: 'Respuestas a las preguntas que más se hacen los padres de bebés, a menudo en plena noche. Cada artículo cita sus fuentes.',
    disclaimer: 'Esta guía es informativa y no sustituye el consejo médico. En caso de emergencia, llama al 112.',
  },
  articles: [
    {
      id: 'fever',
      slug: 'fiebre-bebe-cuando-ir-al-medico',
      emoji: '🌡️',
      title: 'Fiebre en el bebé: ¿cuándo ir al médico?',
      metaTitle: 'Fiebre en el bebé: ¿cuándo ir al médico? Umbrales por edad',
      description: '¿A partir de qué temperatura hay que llevar a un bebé al médico? Umbrales de fiebre según la edad, basados en las guías de la American Academy of Pediatrics.',
      teaser: 'Umbrales de temperatura según la edad.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'En un bebé de menos de 3 meses, cualquier temperatura desde 38,0°C es motivo de consulta urgente, incluso de noche. De 3 a 6 meses, consulta con tu pediatra desde 38,0°C. En niños mayores el umbral para consultar es 39,0°C, y desde 40,5°C cualquier niño necesita atención médica urgente.',
      blocks: [
        { h2: 'Umbrales de fiebre según la edad' },
        { table: {
          head: ['Edad del niño', 'Temperatura', 'Qué hacer'],
          rows: [
            ['Menos de 3 meses', 'desde 38,0°C', 'Al médico con urgencia, incluso de noche', true],
            ['3 a 6 meses', 'desde 38,0°C', 'Consulta con tu pediatra'],
            ['Más de 6 meses', '38,5 a 39,0°C', 'Fiebre alta. Un antitérmico puede mejorar el bienestar del niño, dosis según el prospecto'],
            ['Más de 6 meses', 'desde 39,0°C', 'Consulta con tu pediatra'],
            ['A cualquier edad', 'desde 40,5°C', 'Atención médica urgente', true],
          ],
        } },
        { h2: '¿Por qué el umbral es más bajo en los más pequeños?' },
        { p: 'En los 3 primeros meses el sistema inmunitario aún es inmaduro, y la fiebre puede ser la única señal de una infección grave. Por eso las guías recomiendan una valoración médica urgente aunque el bebé parezca estar bien.' },
        { h2: 'Fiebre de más de 3 días' },
        { p: 'Si un niño mayor de 6 meses tiene fiebre desde hace más de 72 horas, consulta con tu pediatra aunque se le vea bastante bien.' },
        { callout: { title: 'No mires solo el termómetro', text: 'La apatía, la dificultad para despertarlo, la dificultad para respirar, las convulsiones o las manchas que no desaparecen al presionar necesitan ayuda urgente, sea cual sea la temperatura. Lista completa: <a href="/es/guia/senales-de-alarma-bebe/">señales de alarma en el bebé</a>.' } },
        { h2: 'Anota las mediciones con la hora' },
        { p: 'El médico te preguntará desde cuándo dura la fiebre, cuánto subió y cuándo se dio el medicamento. Si anotas las mediciones con la hora, es más fácil responder y ver si la temperatura sube o baja.' },
      ],
      sources: [
        'American Academy of Pediatrics, Clinical Practice Guideline: Evaluation and Management of Well-Appearing Febrile Infants 8 to 60 Days Old (2021)',
        'American Academy of Pediatrics, HealthyChildren.org: Fever',
      ],
      app: 'Mediciones de temperatura con gráfico, medicamentos con la hora y estos umbrales en un solo lugar, también en el móvil del otro progenitor.',
      related: ['warning', 'diapers'],
    },
    {
      id: 'warning',
      slug: 'senales-de-alarma-bebe',
      emoji: '🚨',
      title: 'Señales de alarma en el bebé: cuándo no esperar a mañana',
      metaTitle: 'Señales de alarma en bebés y niños: cuándo ir a urgencias',
      description: '¿Qué síntomas en un bebé o un niño obligan a ir a urgencias o llamar al 112, y cuándo basta con llamar al pediatra? Según las guías de la American Academy of Pediatrics.',
      teaser: 'Cuándo ir a urgencias o llamar al 112.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'No esperes a mañana si un bebé de menos de 3 meses tiene fiebre desde 38°C, si el niño está apático y cuesta despertarlo, tiene dificultad para respirar o los labios azulados, convulsiones, la nuca rígida o manchas que no desaparecen al presionar. Necesita ayuda urgente: ve a urgencias o llama al 112.',
      blocks: [
        { h2: 'Urgente: urgencias o 112' },
        { ol: [
          '<strong>Fiebre desde 38°C en un bebé de menos de 3 meses</strong>, aunque no tenga otros síntomas.',
          '<strong>Temperatura desde 40,5°C</strong> a cualquier edad.',
          '<strong>Apatía, cuesta despertarlo, no reacciona</strong> a la voz ni al tacto.',
          '<strong>Dificultad para respirar</strong>, pitidos, labios azulados.',
          '<strong>Convulsiones, rigidez de nuca</strong> o <strong>manchas que no desaparecen al presionar</strong>.',
        ] },
        { h2: '¿Cómo comprobar si las manchas desaparecen?' },
        { p: 'Presiona con firmeza un vaso transparente sobre las manchas. Si se siguen viendo claramente a través del cristal, no esperes: necesita ayuda urgente.' },
        { h2: 'Consulta con el médico' },
        { ul: [
          '<strong>Señales de deshidratación:</strong> pañal seco más de 6 horas, llanto sin lágrimas, fontanela hundida.',
          '<strong>Vómitos persistentes o diarrea</strong> de más de un día en un lactante.',
          '<strong>Fiebre de más de 72 horas</strong> en un niño mayor de 6 meses.',
        ] },
        { callout: { title: 'Teléfonos', text: 'El <strong>112</strong> es el número de emergencias en toda Europa. Para dudas menos urgentes, llama a tu centro de salud o al teléfono de urgencias sanitarias de tu comunidad autónoma.' } },
        { p: 'Ante la duda, mejor comprobar una vez de más. Los umbrales de fiebre por edad están en el artículo <a href="/es/guia/fiebre-bebe-cuando-ir-al-medico/">fiebre en el bebé: cuándo ir al médico</a>.' },
      ],
      sources: [
        'American Academy of Pediatrics',
        'Mayo Clinic',
      ],
      app: 'La lista de señales de alarma y el 112 están siempre a mano en la app, junto con el historial de mediciones para enseñárselo al médico.',
      related: ['fever', 'diapers'],
    },
    {
      id: 'feeding',
      slug: 'cuantas-tomas-al-dia',
      emoji: '🍼',
      title: '¿Cuántas veces al día come un bebé?',
      metaTitle: '¿Cuántas tomas al día hace un bebé? Rangos según la edad',
      description: '¿Cuántas tomas al día son habituales en un recién nacido, un bebé de 3 meses y un niño de un año? Rangos de la American Academy of Pediatrics, la OMS y la ESPGHAN.',
      teaser: 'Número habitual de tomas, del recién nacido al primer año.',
      basedOn: 'American Academy of Pediatrics, OMS, ESPGHAN',
      answer: 'En el primer mes, un recién nacido suele hacer entre 8 y 12 tomas al día, más o menos cada 2 o 3 horas. Con la edad las tomas se espacian: entre los 4 y los 6 meses suelen ser de 5 a 7, y al final del primer año de 4 a 6 al día.',
      blocks: [
        { h2: 'Tomas de leche al día' },
        { table: {
          head: ['Edad del niño', 'Tomas al día'],
          rows: [
            ['0 a 1 mes', '8 a 12'],
            ['2 a 3 meses', '7 a 9'],
            ['4 a 6 meses', '5 a 7'],
            ['7 a 12 meses', '4 a 6'],
            ['1 a 2 años', '3 a 5'],
          ],
        } },
        { p: 'Contamos las tomas de leche (pecho y biberón), sin las comidas sólidas.' },
        { h2: 'Son rangos, no una norma' },
        { p: 'La alimentación a demanda es lo recomendado por la American Academy of Pediatrics y la OMS. El número de tomas cambia de un día a otro, por ejemplo en los brotes de crecimiento. Más que el número, importa que tu bebé gane peso y moje los pañales. Cómo comprobarlo: <a href="/es/guia/panales-mojados-al-dia/">cuántos pañales mojados son buena señal</a>.' },
        { h2: 'Cuándo hablar con el pediatra' },
        { p: 'Si tienes dudas sobre el aumento de peso o tu bebé moja menos pañales de lo habitual, habla con tu pediatra o con una asesora de lactancia.' },
      ],
      sources: [
        'American Academy of Pediatrics, Breastfeeding and the Use of Human Milk (2022)',
        'OMS, Infant and young child feeding (2021)',
        'ESPGHAN, Complementary Feeding: A Position Paper (2017)',
      ],
      app: 'Anota una toma de pecho o un biberón con un toque. La app cuenta las tomas del día y muestra cuánto hace de la última.',
      related: ['diapers', 'sleep'],
    },
    {
      id: 'diapers',
      slug: 'panales-mojados-al-dia',
      emoji: '💧',
      title: '¿Cuántos pañales mojados al día son buena señal?',
      metaTitle: '¿Cuántos pañales mojados al día? Cómo reconocer la deshidratación',
      description: '¿Cuántos pañales mojados al día debe tener un bebé y cuáles son las señales de deshidratación? Una forma sencilla de saber si tu bebé bebe suficiente.',
      teaser: 'Una forma sencilla de saber si tu bebé está bien hidratado.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'A partir del 5.º día de vida, un bebé suele mojar al menos 6 pañales al día. Menos pañales mojados, un pañal seco durante más de 6 horas, llanto sin lágrimas o la fontanela hundida pueden indicar deshidratación y son motivo para consultar con el médico.',
      blocks: [
        { h2: 'Los primeros días tras el parto' },
        { p: 'Los primeros días hay menos pañales mojados porque todavía hay poca leche. Su número aumenta cada día, y a partir del 5.º día debería haber al menos 6 al día.' },
        { h2: 'Señales de deshidratación' },
        { ul: [
          'Pañal seco más de 6 horas',
          'Llanto sin lágrimas',
          'Fontanela hundida',
          'Menos de 6 pañales mojados al día',
        ] },
        { callout: { title: 'Cuándo ir al médico', text: 'Ante señales de deshidratación, consulta con el médico, sobre todo en un lactante. Los vómitos persistentes o la diarrea de más de un día en un lactante también son motivo para llamar, porque llevan rápido a la deshidratación.' } },
        { h2: 'Contar pañales de noche' },
        { p: 'Después de unas cuantas noches sin dormir cuesta recordar cuántos pañales llevas desde la mañana. Anota cada cambio al momento y con un vistazo sabrás si hoy han sido suficientes.' },
      ],
      sources: [
        'American Academy of Pediatrics',
      ],
      app: 'Anota pañales mojados o sucios con un toque y ve el total del día directamente en la pantalla principal.',
      related: ['feeding', 'warning'],
    },
    {
      id: 'sleep',
      slug: 'cuanto-duerme-un-bebe',
      emoji: '😴',
      title: '¿Cuánto debe dormir un bebé?',
      metaTitle: '¿Cuánto debe dormir un bebé? Sueño al día según la edad',
      description: '¿Cuántas horas al día duerme un recién nacido, un bebé de 4 meses y un niño de un año? Rangos de sueño de la National Sleep Foundation y la American Academy of Pediatrics.',
      teaser: 'Sueño al día según la edad, siestas incluidas.',
      basedOn: 'National Sleep Foundation, American Academy of Pediatrics',
      answer: 'Hasta los 3 meses, un bebé duerme en total de 14 a 17 horas al día, de los 4 a los 11 meses de 12 a 15 horas, y entre 1 y 2 años de 11 a 14 horas, siestas incluidas.',
      blocks: [
        { h2: 'Sueño al día según la edad' },
        { table: {
          head: ['Edad del niño', 'Sueño al día'],
          rows: [
            ['0 a 3 meses', '14 a 17 horas'],
            ['4 a 11 meses', '12 a 15 horas'],
            ['1 a 2 años', '11 a 14 horas'],
            ['3 a 5 años', '10 a 13 horas'],
          ],
        } },
        { p: 'Estos rangos son para todo el día, con las siestas. Cada niño duerme distinto, así que son una referencia y no una norma.' },
        { h2: 'El recién nacido se despierta a menudo' },
        { p: 'Un recién nacido duerme en periodos cortos y se despierta cada 1 a 3 horas, sobre todo para comer. El ritmo de día y noche se suele asentar durante los 2 primeros meses. Ayudan los días luminosos y las noches oscuras y tranquilas.' },
        { h2: 'Peor sueño hacia los 4 meses' },
        { p: 'Hacia los 4 meses, el sueño suele empeorar durante un tiempo. Es una etapa natural del desarrollo del cerebro, no un error de los padres.' },
      ],
      sources: [
        'National Sleep Foundation, Sleep Time Duration Recommendations (2015)',
        'American Academy of Pediatrics, Recommended Amount of Sleep for Pediatric Populations (2016)',
      ],
      app: 'Anota el inicio y el fin del sueño con un toque, y la app suma el sueño y las siestas de todo el día.',
      related: ['feeding', 'fever'],
    },
    // v2 (29/09/2026): temas de la segunda serie de Shorts.
    {
      id: 'thermometer',
      published: '2026-09-29',
      slug: 'como-tomar-la-temperatura-al-bebe',
      emoji: '🌡️',
      title: '¿Cómo tomar la temperatura al bebé?',
      metaTitle: 'Cómo tomar la temperatura al bebé: ¿rectal, axila, oído o frente?',
      description: 'Dónde tomar la temperatura al bebé para un resultado fiable: rectal, en la axila, en el oído o en la frente. Métodos según la edad, según la American Academy of Pediatrics.',
      teaser: 'Qué método a qué edad.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'En bebés menores de 3 meses, la medición rectal es la más precisa. En la axila es lo más fácil pero lo menos preciso, así que comprueba un resultado dudoso de otra forma. El termómetro temporal (frente) sirve desde los 3 meses y el de oído desde los 6 meses.',
      blocks: [
        { h2: 'Métodos según la edad' },
        { table: {
          head: ['Método', 'Desde qué edad', 'Precisión'],
          rows: [
            ['Rectal', 'desde el nacimiento', 'La más precisa, recomendada antes de los 3 meses'],
            ['Frente (termómetro temporal)', 'desde los 3 meses', 'Buena, según las instrucciones del termómetro'],
            ['Oído', 'desde los 6 meses', 'Buena, menos fiable en bebés más pequeños'],
            ['Axila', 'a cualquier edad', 'La menos precisa, útil como primera comprobación'],
          ],
        } },
        { h2: 'Cómo tomar la temperatura rectal con seguridad' },
        { ol: [
          'Usa un termómetro digital y pon un poco de vaselina en la punta.',
          'Tumba al bebé boca arriba con las piernas dobladas hacia la tripa, o boca abajo sobre tus rodillas.',
          'Introduce con suavidad la punta unos 1,5 cm y sujétala hasta que pite.',
          'Después lava el termómetro con agua y jabón y no lo uses en la boca.',
        ] },
        { h2: 'En la axila el valor es más bajo' },
        { p: 'La medición en la axila suele ser más baja que la rectal. Si el resultado está en el límite o el bebé parece enfermo a pesar de un valor bajo, vuelve a medir con un método más preciso.' },
        { callout: { title: '¿Desde cuántos grados es fiebre?', text: 'La fiebre empieza en 38,0 °C. En un bebé menor de 3 meses, cualquier fiebre necesita atención médica urgente. Umbrales para niños mayores: <a href="/es/guia/fiebre-bebe-cuando-ir-al-medico/">fiebre en el bebé: cuándo ir al médico</a>.' } },
      ],
      sources: [
        'American Academy of Pediatrics, How to Take a Child’s Temperature (healthychildren.org)',
      ],
      app: 'Guarda las mediciones con la hora y el método, y la gráfica muestra si la temperatura sube o baja.',
      related: ['fever', 'warning'],
    },
    {
      id: 'glass',
      published: '2026-09-29',
      slug: 'prueba-del-vaso-manchas',
      emoji: '🥛',
      title: 'La prueba del vaso: erupción y fiebre en el niño',
      metaTitle: 'Prueba del vaso ante manchas en la piel: cuándo llamar al 112',
      description: 'Cómo hacer la prueba del vaso ante una erupción con fiebre y qué significa el resultado. Las manchas que no desaparecen bajo el vaso pueden indicar una infección meningocócica.',
      teaser: 'Manchas que no desaparecen bajo el vaso.',
      basedOn: 'NHS, Meningitis Research Foundation',
      answer: 'Presiona un vaso transparente sobre la erupción y mira a través. Si las manchas desaparecen, vigila al niño y llama al pediatra si tiene fiebre. Si las manchas NO desaparecen con la presión, llama al 112 ahora mismo: puede ser una infección meningocócica.',
      blocks: [
        { h2: 'Cómo hacer la prueba del vaso' },
        { ol: [
          'Coge un vaso transparente de paredes lisas.',
          'Presiona con firmeza la pared del vaso sobre las manchas.',
          'Mira a través del vidrio si las manchas palidecen y desaparecen con la presión.',
        ] },
        { table: {
          head: ['Resultado', 'Lo que ves', 'Qué hacer'],
          rows: [
            ['Las manchas desaparecen', 'se borran bajo el vaso', 'Vigila al niño. Si tiene fiebre, llama al pediatra.'],
            ['Las manchas NO desaparecen', 'se ven a través del vaso', 'Llama al 112 ahora mismo', true],
          ],
        } },
        { h2: 'Piel oscura' },
        { p: 'En la piel oscura la erupción se ve peor. Mira las zonas más claras: palmas, plantas de los pies, el interior de los párpados y el paladar.' },
        { callout: { title: 'La prueba no lo es todo', text: 'Al principio de la enfermedad, las manchas pueden desaparecer todavía. Si tu hijo parece muy enfermo, está adormilado, tiene las manos y los pies fríos o empeora deprisa, llama al 112 sea cual sea el resultado. Todas las señales: <a href="/es/guia/senales-de-alarma-bebe/">señales de alarma en el bebé</a>.' } },
      ],
      sources: [
        'NHS, Meningitis: symptoms and the glass test (nhs.uk)',
        'Meningitis Research Foundation',
      ],
      app: 'Las señales de alarma y el 112 están siempre a mano en la app, junto con el historial de temperatura para enseñarlo al médico.',
      related: ['warning', 'fever'],
    },
    {
      id: 'teeth',
      published: '2026-09-29',
      slug: 'cuando-salen-los-dientes-al-bebe',
      emoji: '🦷',
      title: '¿Cuándo salen los dientes al bebé?',
      metaTitle: '¿Cuándo salen los dientes al bebé? Orden de los dientes de leche',
      description: 'A qué edad sale el primer diente y en qué orden salen los dientes de leche. Tabla según la American Academy of Pediatric Dentistry.',
      teaser: 'Orden de los dientes de leche en meses.',
      basedOn: 'American Academy of Pediatric Dentistry, American Academy of Pediatrics',
      answer: 'Suelen salir primero los incisivos centrales de abajo, entre los 6 y los 10 meses, y después los de arriba (8 a 12 meses) y los laterales. Cada niño tiene su ritmo. Si a los 18 meses no hay ningún diente, consulta al dentista. La dentición no da fiebre alta.',
      blocks: [
        { h2: 'Dientes de leche: edad habitual' },
        { table: {
          head: ['Diente', 'Edad (meses)', 'Nota'],
          rows: [
            ['Centrales abajo', '6-10', 'Suelen ser los primeros'],
            ['Centrales arriba', '8-12', ''],
            ['Laterales arriba', '9-13', ''],
            ['Laterales abajo', '10-16', ''],
            ['Primeros molares', '13-19', ''],
            ['Colmillos', '16-23', ''],
            ['Segundos molares', '23-33', 'Suelen ser los últimos'],
          ],
        } },
        { h2: 'Señales de dentición' },
        { p: 'Babeo, morderlo todo, irritabilidad y peor sueño son típicos. Ayudan un mordedor frío (no congelado) y masajear las encías con un dedo limpio.' },
        { callout: { title: 'La fiebre no es de los dientes', text: 'La dentición puede subir un poco la temperatura, pero no da fiebre de 38 °C o más. Si tu bebé tiene fiebre, busca otra causa y consulta con el médico. Umbrales según la edad: <a href="/es/guia/fiebre-bebe-cuando-ir-al-medico/">fiebre en el bebé</a>.' } },
        { h2: 'Primera visita al dentista' },
        { p: 'Pide la primera cita con el odontopediatra cuando salga el primer diente, y como muy tarde hacia el primer cumpleaños.' },
      ],
      sources: [
        'American Academy of Pediatric Dentistry, Dental Growth and Development',
        'American Academy of Pediatrics, Teething (healthychildren.org)',
      ],
      app: 'En la pestaña Dientes marcas cada diente con su fecha, y la gráfica lo compara con los rangos habituales.',
      related: ['fever', 'sleep'],
    },
    {
      id: 'croup',
      published: '2026-09-29',
      slug: 'tos-perruna-crup',
      emoji: '🐕',
      title: 'Tos perruna por la noche: el crup en niños',
      metaTitle: 'Tos perruna en niños (crup): qué hacer y cuándo llamar al 112',
      description: 'Una tos como un ladrido, ronquera y ruido al inspirar. Cómo reconocer el crup (laringitis), qué hacer por la noche y cuándo llamar al 112.',
      teaser: 'Qué hacer por la noche y cuándo llamar al 112.',
      basedOn: 'NHS, American Academy of Pediatrics',
      answer: 'Una tos perruna y ronquera, que suelen empeorar por la noche, son típicas del crup, una inflamación de la laringe. Calma al niño y mantenlo erguido. Llama al 112 si hay ruido agudo al inspirar en reposo, la piel se hunde entre las costillas, los labios se ponen azulados o el niño babea y no puede tragar.',
      blocks: [
        { h2: 'Cómo reconocer el crup' },
        { ul: [
          '<strong>Tos como el ladrido de un perro</strong> o de una foca.',
          '<strong>Ronquera</strong> y voz cambiada.',
          '<strong>Ruido agudo al inspirar</strong>, a menudo al llorar.',
          'Los síntomas suelen <strong>empeorar por la noche</strong> y duran unos días.',
        ] },
        { h2: 'Qué hacer' },
        { p: 'Calma al niño y mantenlo sentado o erguido: el llanto y el miedo empeoran la dificultad para respirar. Si tiene fiebre o dolor, puedes darle un antitérmico según el prospecto. Llama al pediatra, sobre todo si los síntomas no mejoran.' },
        { h2: 'Urgente: 112' },
        { ol: [
          '<strong>Ruido agudo al inspirar incluso en reposo</strong>, cuando el niño está tranquilo.',
          '<strong>La piel se hunde</strong> entre las costillas o bajo el esternón.',
          '<strong>Labios azulados</strong> o piel muy pálida, grisácea.',
          '<strong>Babea</strong> y no puede tragar.',
          '<strong>Somnolencia</strong>, el niño está agotado de respirar.',
        ] },
        { callout: { title: 'Peor por la noche, mejor por la mañana', text: 'El crup suele empeorar por la noche y mejorar por la mañana. Si por la noche hubo dificultad para respirar, consulta con el pediatra aunque por la mañana esté mejor. Otras señales urgentes: <a href="/es/guia/senales-de-alarma-bebe/">señales de alarma en el bebé</a>.' } },
      ],
      sources: [
        'NHS, Croup (nhs.uk)',
        'American Academy of Pediatrics, Croup and Your Young Child (healthychildren.org)',
      ],
      app: 'Anota los episodios de tos con el momento del día y la intensidad, y la app te avisa ante una tos perruna o sibilante.',
      related: ['warning', 'fever'],
    },
    {
      id: 'solids',
      published: '2026-09-29',
      slug: 'cuando-empezar-alimentacion-complementaria',
      emoji: '🥕',
      title: '¿Cuándo empezar la alimentación complementaria?',
      metaTitle: '¿Cuándo empezar con sólidos? 4 señales de que tu bebé está listo',
      description: 'Desde cuándo dar alimentos sólidos al bebé, cómo saber si está listo y qué evitar. Según la OMS, la ESPGHAN y la American Academy of Pediatrics.',
      teaser: 'Señales de que está listo y qué evitar.',
      basedOn: 'OMS, ESPGHAN, American Academy of Pediatrics',
      answer: 'Normalmente hacia los 6 meses, y nunca antes de los 4 meses. Tu bebé está listo cuando se sienta con apoyo, sostiene bien la cabeza, muestra interés por la comida y ya no empuja la cuchara con la lengua. Nada de miel antes de los 12 meses.',
      blocks: [
        { h2: 'Señales de que está listo' },
        { ol: [
          '<strong>Se sienta con apoyo</strong> sin caerse.',
          '<strong>Sostiene bien la cabeza.</strong>',
          '<strong>Muestra interés por la comida</strong>, la intenta coger, abre la boca.',
          '<strong>Ya no empuja la cuchara con la lengua.</strong>',
        ] },
        { h2: 'Cómo empezar' },
        { ul: [
          'Introduce los alimentos nuevos <strong>de uno en uno, cada 3-4 días</strong>: así es más fácil detectar alergias.',
          'La leche (materna o de fórmula) sigue siendo el alimento principal el primer año.',
          'Ofrece trozos blandos o purés adaptados a lo que tu bebé sabe hacer.',
        ] },
        { h2: 'Qué evitar' },
        { table: {
          head: ['Alimento', 'Desde cuándo', 'Por qué'],
          rows: [
            ['Miel', 'después de los 12 meses', 'Riesgo de botulismo', true],
            ['Frutos secos enteros', 'después de los 5 años', 'Riesgo de atragantamiento', true],
            ['Leche de vaca como bebida', 'después de los 12 meses', 'Poco hierro'],
          ],
        } },
        { callout: { title: 'Alérgenos', text: 'No hace falta retrasar alérgenos comunes como el huevo o la crema de cacahuete lisa. Si hay alergias alimentarias en la familia, haz un plan con tu pediatra.' } },
      ],
      sources: [
        'OMS, Alimentación complementaria',
        'ESPGHAN, Complementary Feeding: A Position Paper (2017)',
        'American Academy of Pediatrics, Starting Solid Foods (healthychildren.org)',
      ],
      app: 'En la pestaña Alimentación marcas qué ha probado tu bebé y si hubo alguna reacción.',
      related: ['feeding', 'teeth'],
    },
  ],
}
