// Contenu FR : page de l’appli /fr/ et guide /fr/guide/.
// Mêmes valeurs que la version française de l’appli. Vouvoiement.
// Les espaces avant « ? : ! ; » deviennent insécables à la génération.

export default {
  lang: 'fr',
  ogLocale: 'fr_FR',
  currency: 'EUR',
  appName: 'Calm Parent',
  appPath: '/fr/',
  guidePath: '/fr/guide/',
  ui: {
    navGuide: 'guide',
    navApp: 'appli',
    guideName: 'Guide',
    cta: 'Disponible sur Google Play',
    answer: 'En bref',
    updated: 'Mis à jour le',
    date: '27 septembre 2026',
    basedOn: 'D’après',
    sources: 'Sources',
    related: 'À lire aussi',
    appSuffix: 'Sans publicité, 14 jours de Premium offerts.',
    articleDisclaimer: 'Cet article est informatif et ne remplace pas l’avis d’un médecin. En cas de doute, contactez un médecin. En cas d’urgence vitale, appelez le 15 ou le 112.',
    footer: 'Calm Parent · un projet <a href="/" style="color:var(--accent-dim);text-decoration:none;">skudev</a> · 2026',
    privacy: 'confidentialité',
  },
  landing: {
    title: 'Calm Parent : le carnet de bébé pour les deux parents · Android',
    description: 'Repas, sommeil, couches et fièvre d’un seul appui. Un Premium pour les deux parents, seuils de fièvre issus des recommandations pédiatriques et rapport PDF pour le médecin. Sans publicité. Appli Android sur Google Play.',
    eyebrow: '// Appli pour les parents · Android',
    h1: 'Le carnet de bébé <em>pour les deux</em> parents.',
    lead: 'Repas, sommeil, couches et fièvre d’un seul appui. Vous voyez tous les deux les mêmes entrées, chacun sur son téléphone. Seuils de fièvre issus des recommandations pédiatriques et rapport PDF pour la consultation. Sans publicité.',
    guideButton: 'Guide pour les parents',
    status: 'sur Google Play · français, anglais, allemand, espagnol, polonais',
    storyLabel: '// pourquoi cette appli',
    story: 'Notre enfant a eu de la fièvre en pleine nuit. J’ai cherché sur Google quoi faire, et chaque site disait autre chose. <em>Je voulais tout au même endroit</em> : les mesures, les médicaments donnés avec l’heure et les seuils des recommandations pédiatriques. C’est ainsi qu’est né Calm Parent.',
    storyAuthor: 'Mateusz, papa et créateur de l’appli',
    featuresLabel: '// ce que vous obtenez',
    featuresTitle: 'Six choses qui me <em>manquaient</em> dans les autres applis.',
    features: [
      { emoji: '🍼', title: 'Noté d’un seul appui', text: 'Allaitement ou biberon, sommeil et couches. Avec le widget de l’écran d’accueil, vous notez un repas sans ouvrir l’appli.' },
      { emoji: '👨‍👩‍👧', title: 'Un Premium pour les deux', text: 'Invitez votre partenaire avec un code et vous voyez tous les deux les mêmes entrées en temps réel. Un seul paie, Premium marche pour les deux.' },
      { emoji: '🌡️', title: 'Température avec courbe', text: 'Mesures avec l’heure et courbe de tendance. À côté, les seuils de référence des recommandations pédiatriques, à lire à tout moment.' },
      { emoji: '💊', title: 'Médicaments et rappels', text: 'Vous notez quel médicament a été donné et à quelle heure. Le rappel arrive sur les deux téléphones. L’appli ne calcule pas les doses, vérifiez toujours la notice.' },
      { emoji: '📊', title: 'Courbes OMS et rapport PDF', text: 'Poids, taille et périmètre crânien sur les courbes de percentiles OMS. Un rapport PDF de la période choisie à apporter au pédiatre.' },
      { emoji: '🔒', title: 'Sans pub, données dans l’UE', text: 'Pas de publicité ni de vente de données. Vos données sont stockées sur des serveurs dans l’Union européenne, avec export CSV à tout moment.' },
    ],
    previewLabel: '// aperçu de l’appli',
    previewTitle: 'Pensée pour <em>noter vite</em>, d’une seule main.',
    phones: [
      { img: 'dzis', label: '01 · Aujourd’hui', title: 'Toute la journée sur un écran', desc: 'Repas, sommeil, couches et dernière température.', alt: 'Écran Aujourd’hui : repas, sommeil, couches et dernière température' },
      { img: 'karmienie', label: '02 · Repas', title: 'Un repas noté en 2 secondes', desc: 'Sein, biberon et heure d’un seul appui.', alt: 'Écran repas : sein gauche, sein droit, biberon' },
      { img: 'wspolne-konto', label: '03 · Compte partagé', title: 'Un Premium pour les deux', desc: 'Les mêmes entrées sur vos deux téléphones, en temps réel.', alt: 'Compte partagé : code d’invitation pour l’autre parent' },
    ],
    guidesLabel: '// guide',
    ctaLabel: '// télécharger',
    ctaTitle: '14 jours de Premium <em>offerts</em>, sans carte.',
    ctaLead: 'Après 14 jours, vous gardez la version de base : noter repas, sommeil, température et médicaments reste gratuit. Vous achetez Premium seulement si vous le souhaitez.',
    disclaimer: 'Calm Parent n’est pas un dispositif médical. L’appli ne pose pas de diagnostic, ne calcule pas les doses et ne remplace pas un médecin. En cas d’urgence vitale, appelez le 15 ou le 112.',
  },
  index: {
    title: 'Guide pour les parents de bébés',
    description: 'Fièvre, repas, couches, sommeil et signes d’alerte chez bébé. Court et clair, d’après les recommandations pédiatriques.',
    eyebrow: '// Guide pour les parents',
    h1: 'Court et clair, <em>d’après les recommandations</em> pédiatriques.',
    lead: 'Des réponses aux questions que les parents de bébés se posent le plus, souvent en pleine nuit. Chaque article cite ses sources.',
    disclaimer: 'Ce guide est informatif et ne remplace pas l’avis d’un médecin. En cas d’urgence vitale, appelez le 15 ou le 112.',
  },
  articles: [
    {
      id: 'fever',
      slug: 'fievre-bebe-quand-consulter',
      emoji: '🌡️',
      title: 'Fièvre chez bébé : quand consulter ?',
      metaTitle: 'Fièvre chez bébé : quand consulter ? Seuils selon l’âge',
      description: 'À partir de quelle température faut-il consulter avec un bébé ? Seuils de fièvre selon l’âge, d’après les recommandations de l’American Academy of Pediatrics.',
      teaser: 'Seuils de température selon l’âge.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'Chez un bébé de moins de 3 mois, toute température dès 38,0°C impose une consultation urgente, même la nuit. De 3 à 6 mois, appelez le médecin dès 38,0°C. Chez les enfants plus grands, le seuil pour consulter est de 39,0°C, et dès 40,5°C, tout enfant a besoin d’une aide médicale urgente.',
      blocks: [
        { h2: 'Seuils de fièvre selon l’âge' },
        { table: {
          head: ['Âge de l’enfant', 'Température', 'Que faire'],
          rows: [
            ['Moins de 3 mois', 'dès 38,0°C', 'Consultez en urgence, même la nuit', true],
            ['3 à 6 mois', 'dès 38,0°C', 'Appelez le médecin'],
            ['Plus de 6 mois', '38,5 à 39,0°C', 'Fièvre élevée. Un antipyrétique peut améliorer le confort de l’enfant, dose selon la notice'],
            ['Plus de 6 mois', 'dès 39,0°C', 'Appelez le médecin'],
            ['À tout âge', 'dès 40,5°C', 'Aide médicale urgente', true],
          ],
        } },
        { h2: 'Pourquoi le seuil est-il plus bas chez les plus petits ?' },
        { p: 'Pendant les 3 premiers mois, le système immunitaire est encore immature et la fièvre peut être le seul signe d’une infection grave. C’est pourquoi les recommandations prévoient un examen médical urgent, même si le bébé semble par ailleurs aller bien.' },
        { h2: 'Fièvre de plus de 3 jours' },
        { p: 'Si un enfant de plus de 6 mois a de la fièvre depuis plus de 72 heures, appelez le médecin, même s’il semble plutôt en forme.' },
        { callout: { title: 'Ne regardez pas que le thermomètre', text: 'Apathie, difficulté à réveiller, gêne respiratoire, convulsions ou taches qui ne s’effacent pas à la pression nécessitent une aide urgente, quelle que soit la température. La liste complète : <a href="/fr/guide/signes-d-alerte-bebe/">signes d’alerte chez bébé</a>.' } },
        { h2: 'Notez les mesures avec l’heure' },
        { p: 'Le médecin vous demandera depuis quand dure la fièvre, jusqu’où elle est montée et quand un médicament a été donné. Si vous notez les mesures avec l’heure, il est plus facile de répondre et de voir si la température monte ou baisse.' },
      ],
      sources: [
        'American Academy of Pediatrics, Clinical Practice Guideline: Evaluation and Management of Well-Appearing Febrile Infants 8 to 60 Days Old (2021)',
        'American Academy of Pediatrics, HealthyChildren.org: Fever',
      ],
      app: 'Mesures de température avec courbe, médicaments donnés avec l’heure et ces seuils au même endroit, aussi sur le téléphone de l’autre parent.',
      related: ['warning', 'diapers'],
    },
    {
      id: 'warning',
      slug: 'signes-d-alerte-bebe',
      emoji: '🚨',
      title: 'Signes d’alerte chez bébé : quand ne pas attendre le matin',
      metaTitle: 'Signes d’alerte chez bébé et l’enfant : quand appeler le 15',
      description: 'Quels symptômes chez un bébé ou un enfant imposent d’aller aux urgences ou d’appeler le 15, et quand suffit-il d’appeler le médecin ? D’après les recommandations de l’American Academy of Pediatrics.',
      teaser: 'Quand aller aux urgences ou appeler le 15.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'N’attendez pas le matin si un bébé de moins de 3 mois a une fièvre dès 38°C, si l’enfant est apathique et difficile à réveiller, a du mal à respirer ou les lèvres bleutées, fait des convulsions, a la nuque raide ou des taches qui ne s’effacent pas à la pression. Il faut une aide urgente : appelez le 15 ou le 112.',
      blocks: [
        { h2: 'Urgent : appelez le 15 ou le 112' },
        { ol: [
          '<strong>Fièvre dès 38°C chez un bébé de moins de 3 mois</strong>, même sans autre symptôme.',
          '<strong>Température dès 40,5°C</strong> à tout âge.',
          '<strong>Apathie, difficile à réveiller, ne réagit pas</strong> à la voix ni au toucher.',
          '<strong>Difficulté à respirer</strong>, sifflements, lèvres bleutées.',
          '<strong>Convulsions, raideur de la nuque</strong> ou <strong>taches qui ne s’effacent pas à la pression</strong>.',
        ] },
        { h2: 'Comment vérifier si les taches s’effacent ?' },
        { p: 'Appuyez fermement un verre transparent sur l’éruption. Si les taches restent bien visibles à travers le verre, n’attendez pas : il faut une aide urgente.' },
        { h2: 'Appelez le médecin' },
        { ul: [
          '<strong>Signes de déshydratation :</strong> couche sèche depuis plus de 6 heures, pleurs sans larmes, fontanelle creusée.',
          '<strong>Vomissements persistants ou diarrhée</strong> de plus d’une journée chez un nourrisson.',
          '<strong>Fièvre de plus de 72 heures</strong> chez un enfant de plus de 6 mois.',
        ] },
        { callout: { title: 'Numéros', text: 'Le <strong>15</strong> (SAMU) pour une urgence médicale, le <strong>112</strong> dans toute l’Europe. Pour un conseil moins urgent la nuit ou le week-end, appelez votre médecin ou le <strong>116 117</strong> (permanence des soins, selon les régions).' } },
        { p: 'En cas de doute, mieux vaut vérifier une fois de trop. Les seuils de fièvre selon l’âge sont dans l’article <a href="/fr/guide/fievre-bebe-quand-consulter/">fièvre chez bébé : quand consulter</a>.' },
      ],
      sources: [
        'American Academy of Pediatrics',
        'Mayo Clinic',
      ],
      app: 'La liste des signes d’alerte et les numéros d’urgence sont toujours à portée de main dans l’appli, avec l’historique des mesures à montrer au médecin.',
      related: ['fever', 'diapers'],
    },
    {
      id: 'feeding',
      slug: 'combien-de-repas-bebe',
      emoji: '🍼',
      title: 'Combien de fois par jour mange un bébé ?',
      metaTitle: 'Combien de tétées ou biberons par jour ? Repères selon l’âge',
      description: 'Combien de repas par jour sont habituels pour un nouveau-né, un bébé de 3 mois et un enfant d’un an ? Repères de l’American Academy of Pediatrics, de l’OMS et de l’ESPGHAN.',
      teaser: 'Nombre habituel de repas, du nouveau-né à un an.',
      basedOn: 'American Academy of Pediatrics, OMS, ESPGHAN',
      answer: 'Le premier mois, un nouveau-né mange en général 8 à 12 fois par jour, soit environ toutes les 2 à 3 heures. Avec l’âge, les repas s’espacent : en général 5 à 7 par jour entre 4 et 6 mois, et 4 à 6 à la fin de la première année.',
      blocks: [
        { h2: 'Repas de lait par jour' },
        { table: {
          head: ['Âge de l’enfant', 'Repas par jour'],
          rows: [
            ['0 à 1 mois', '8 à 12'],
            ['2 à 3 mois', '7 à 9'],
            ['4 à 6 mois', '5 à 7'],
            ['7 à 12 mois', '4 à 6'],
            ['1 à 2 ans', '3 à 5'],
          ],
        } },
        { p: 'Nous comptons les repas de lait (sein et biberon), sans les repas solides.' },
        { h2: 'Des repères, pas une norme' },
        { p: 'Nourrir à la demande est la règle selon l’American Academy of Pediatrics et l’OMS. Le nombre de repas varie d’un jour à l’autre, par exemple pendant les pics de croissance. Plus que le nombre, ce qui compte est que bébé prenne du poids et mouille ses couches. Comment le vérifier : <a href="/fr/guide/couches-mouillees-par-jour/">combien de couches mouillées, c’est bon signe</a>.' },
        { h2: 'Quand en parler au médecin' },
        { p: 'Si vous avez un doute sur la prise de poids ou si bébé mouille moins de couches que d’habitude, parlez-en à votre médecin ou à une consultante en lactation.' },
      ],
      sources: [
        'American Academy of Pediatrics, Breastfeeding and the Use of Human Milk (2022)',
        'OMS, Infant and young child feeding (2021)',
        'ESPGHAN, Complementary Feeding: A Position Paper (2017)',
      ],
      app: 'Notez une tétée ou un biberon d’un seul appui. L’appli compte les repas de la journée et affiche le temps écoulé depuis le dernier.',
      related: ['diapers', 'sleep'],
    },
    {
      id: 'diapers',
      slug: 'couches-mouillees-par-jour',
      emoji: '💧',
      title: 'Combien de couches mouillées par jour, c’est bon signe ?',
      metaTitle: 'Combien de couches mouillées par jour ? Reconnaître la déshydratation',
      description: 'Combien de couches mouillées par jour un bébé doit-il avoir, et quels sont les signes de déshydratation ? Un repère simple pour savoir si bébé boit assez.',
      teaser: 'Un repère simple pour savoir si bébé boit assez.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'À partir du 5e jour environ, un bébé mouille en général au moins 6 couches par jour. Moins de couches mouillées, une couche sèche depuis plus de 6 heures, des pleurs sans larmes ou une fontanelle creusée peuvent signaler une déshydratation et sont une raison de contacter un médecin.',
      blocks: [
        { h2: 'Les premiers jours après la naissance' },
        { p: 'Les premiers jours, il y a moins de couches mouillées, car il y a encore peu de lait. Leur nombre augmente jour après jour, et à partir du 5e jour environ, il devrait y en avoir au moins 6 par jour.' },
        { h2: 'Signes de déshydratation' },
        { ul: [
          'Couche sèche depuis plus de 6 heures',
          'Pleurs sans larmes',
          'Fontanelle creusée',
          'Moins de 6 couches mouillées par jour',
        ] },
        { callout: { title: 'Quand consulter', text: 'Devant des signes de déshydratation, contactez un médecin, surtout chez un nourrisson. Des vomissements persistants ou une diarrhée de plus d’une journée chez un nourrisson sont aussi une raison d’appeler, car ils mènent vite à la déshydratation.' } },
        { h2: 'Compter les couches la nuit' },
        { p: 'Après quelques nuits blanches, difficile de se souvenir du nombre de couches depuis le matin. Notez chaque change tout de suite : un coup d’œil suffit pour savoir si la journée a été suffisante.' },
      ],
      sources: [
        'American Academy of Pediatrics',
      ],
      app: 'Notez les couches mouillées ou sales d’un seul appui et voyez le total de la journée directement sur l’écran d’accueil.',
      related: ['feeding', 'warning'],
    },
    {
      id: 'sleep',
      slug: 'combien-dort-bebe',
      emoji: '😴',
      title: 'Combien de temps doit dormir un bébé ?',
      metaTitle: 'Combien de temps dort un bébé ? Sommeil par jour selon l’âge',
      description: 'Combien d’heures par jour dort un nouveau-né, un bébé de 4 mois et un enfant d’un an ? Repères de la National Sleep Foundation et de l’American Academy of Pediatrics.',
      teaser: 'Sommeil par jour selon l’âge, siestes comprises.',
      basedOn: 'National Sleep Foundation, American Academy of Pediatrics',
      answer: 'Jusqu’à 3 mois, un bébé dort au total 14 à 17 heures par jour, de 4 à 11 mois 12 à 15 heures, et entre 1 et 2 ans 11 à 14 heures, siestes comprises.',
      blocks: [
        { h2: 'Sommeil par jour selon l’âge' },
        { table: {
          head: ['Âge de l’enfant', 'Sommeil par jour'],
          rows: [
            ['0 à 3 mois', '14 à 17 heures'],
            ['4 à 11 mois', '12 à 15 heures'],
            ['1 à 2 ans', '11 à 14 heures'],
            ['3 à 5 ans', '10 à 13 heures'],
          ],
        } },
        { p: 'Ces repères valent pour toute la journée, siestes comprises. Chaque enfant dort différemment : c’est une référence, pas une norme.' },
        { h2: 'Le nouveau-né se réveille souvent' },
        { p: 'Un nouveau-né dort par courtes périodes et se réveille toutes les 1 à 3 heures, surtout pour manger. Le rythme jour et nuit se met en place en général pendant les 2 premiers mois. Des journées lumineuses et des nuits sombres et calmes aident.' },
        { h2: 'Sommeil moins bon vers 4 mois' },
        { p: 'Vers 4 mois, le sommeil se dégrade souvent pendant un temps. C’est une étape naturelle du développement du cerveau, pas une erreur des parents.' },
      ],
      sources: [
        'National Sleep Foundation, Sleep Time Duration Recommendations (2015)',
        'American Academy of Pediatrics, Recommended Amount of Sleep for Pediatric Populations (2016)',
      ],
      app: 'Notez le début et la fin du sommeil d’un seul appui : l’appli additionne sommeil et siestes de toute la journée.',
      related: ['feeding', 'fever'],
    },
    // v2 (29/09/2026) : sujets de la deuxième série de Shorts.
    {
      id: 'thermometer',
      published: '2026-09-29',
      slug: 'prendre-la-temperature-de-bebe',
      emoji: '🌡️',
      title: 'Comment prendre la température de bébé ?',
      metaTitle: 'Prendre la température de bébé : rectale, aisselle, oreille ou front ?',
      description: 'Où prendre la température de bébé pour un résultat fiable : rectale, sous l’aisselle, dans l’oreille ou sur le front. Méthodes selon l’âge, d’après l’American Academy of Pediatrics.',
      teaser: 'Quelle méthode à quel âge.',
      basedOn: 'American Academy of Pediatrics',
      answer: 'Chez le bébé de moins de 3 mois, la mesure rectale est la plus précise. Sous l’aisselle, c’est le plus simple mais le moins précis : vérifiez un résultat douteux autrement. Le thermomètre temporal (front) convient dès 3 mois et le thermomètre auriculaire dès 6 mois.',
      blocks: [
        { h2: 'Méthodes selon l’âge' },
        { table: {
          head: ['Méthode', 'À partir de', 'Précision'],
          rows: [
            ['Rectale', 'la naissance', 'La plus précise, recommandée avant 3 mois'],
            ['Front (thermomètre temporal)', '3 mois', 'Bonne, selon la notice du thermomètre'],
            ['Oreille', '6 mois', 'Bonne, moins fiable chez les plus petits'],
            ['Sous l’aisselle', 'tout âge', 'La moins précise, utile pour un premier contrôle'],
          ],
        } },
        { h2: 'Prendre la température rectale sans risque' },
        { ol: [
          'Utilisez un thermomètre électronique et mettez un peu de vaseline sur l’embout.',
          'Allongez bébé sur le dos, jambes repliées vers le ventre, ou sur le ventre sur vos genoux.',
          'Introduisez doucement l’embout d’environ 1,5 cm et maintenez-le jusqu’au bip.',
          'Lavez ensuite le thermomètre à l’eau et au savon et ne l’utilisez plus dans la bouche.',
        ] },
        { h2: 'Sous l’aisselle, la valeur est plus basse' },
        { p: 'La mesure sous l’aisselle est en général plus basse que la mesure rectale. Si le résultat est limite, ou si bébé semble malade malgré une valeur basse, mesurez à nouveau avec une méthode plus précise.' },
        { callout: { title: 'À partir de quand parle-t-on de fièvre ?', text: 'La fièvre commence à 38,0 °C. Chez un bébé de moins de 3 mois, toute fièvre nécessite un avis médical urgent. Seuils pour les enfants plus grands : <a href="/fr/guide/fievre-bebe-quand-consulter/">fièvre chez bébé : quand consulter</a>.' } },
      ],
      sources: [
        'American Academy of Pediatrics, How to Take a Child’s Temperature (healthychildren.org)',
      ],
      app: 'Enregistrez les mesures avec l’heure et la méthode, et la courbe montre si la température monte ou baisse.',
      related: ['fever', 'warning'],
    },
    {
      id: 'glass',
      published: '2026-09-29',
      slug: 'test-du-verre-purpura',
      emoji: '🥛',
      title: 'Le test du verre : éruption et fièvre chez l’enfant',
      metaTitle: 'Test du verre en cas de taches : quand appeler le 15',
      description: 'Comment faire le test du verre en cas d’éruption avec fièvre et ce que signifie le résultat. Des taches qui ne s’effacent pas sous le verre peuvent signaler une infection à méningocoque (purpura).',
      teaser: 'Des taches qui ne s’effacent pas sous le verre.',
      basedOn: 'NHS, Meningitis Research Foundation',
      answer: 'Appuyez un verre transparent sur l’éruption et regardez à travers. Si les taches s’effacent, surveillez l’enfant et appelez le médecin en cas de fièvre. Si les taches ne s’effacent PAS sous la pression, appelez tout de suite le 15 ou le 112 : cela peut être une infection à méningocoque.',
      blocks: [
        { h2: 'Comment faire le test du verre' },
        { ol: [
          'Prenez un verre transparent aux parois lisses.',
          'Appuyez fermement la paroi du verre sur les taches.',
          'Regardez à travers le verre si les taches pâlissent et disparaissent sous la pression.',
        ] },
        { table: {
          head: ['Résultat', 'Ce que vous voyez', 'Que faire'],
          rows: [
            ['Les taches s’effacent', 'elles disparaissent sous le verre', 'Surveillez l’enfant. En cas de fièvre, appelez le médecin.'],
            ['Les taches ne s’effacent PAS', 'visibles à travers le verre', 'Appelez tout de suite le 15 ou le 112', true],
          ],
        } },
        { h2: 'Peau foncée' },
        { p: 'Sur une peau foncée, l’éruption est plus difficile à voir. Regardez les zones plus claires : paumes, plantes des pieds, intérieur des paupières et palais.' },
        { callout: { title: 'Le test ne dit pas tout', text: 'Au début de la maladie, les taches peuvent encore s’effacer. Si l’enfant semble très malade, somnolent, a les mains et les pieds froids ou s’aggrave vite, appelez le 15, quel que soit le résultat du test. Tous les signes d’alerte : <a href="/fr/guide/signes-d-alerte-bebe/">signes d’alerte chez bébé</a>.' } },
      ],
      sources: [
        'NHS, Meningitis: symptoms and the glass test (nhs.uk)',
        'Meningitis Research Foundation',
      ],
      app: 'Les signes d’alerte et les numéros d’urgence sont toujours à portée de main dans l’appli, avec l’historique de température à montrer au médecin.',
      related: ['warning', 'fever'],
    },
    {
      id: 'teeth',
      published: '2026-09-29',
      slug: 'quand-sortent-les-dents-de-bebe',
      emoji: '🦷',
      title: 'Quand sortent les dents de bébé ?',
      metaTitle: 'Quand sortent les dents de bébé ? L’ordre des dents de lait',
      description: 'À quel âge sort la première dent et dans quel ordre poussent les dents de lait. Tableau d’après l’American Academy of Pediatric Dentistry.',
      teaser: 'L’ordre des dents de lait en mois.',
      basedOn: 'American Academy of Pediatric Dentistry, American Academy of Pediatrics',
      answer: 'Les incisives du bas sortent en général en premier, entre 6 et 10 mois, puis les incisives du haut (8 à 12 mois) et les latérales. Chaque enfant a son rythme. Pas de dent à 18 mois ? Demandez au dentiste. Les poussées dentaires ne donnent pas de forte fièvre.',
      blocks: [
        { h2: 'Dents de lait : âge habituel' },
        { table: {
          head: ['Dent', 'Âge (mois)', 'Remarque'],
          rows: [
            ['Devant, en bas', '6-10', 'En général les premières'],
            ['Devant, en haut', '8-12', ''],
            ['Côtés, en haut', '9-13', ''],
            ['Côtés, en bas', '10-16', ''],
            ['Premières molaires', '13-19', ''],
            ['Canines', '16-23', ''],
            ['Deuxièmes molaires', '23-33', 'En général les dernières'],
          ],
        } },
        { h2: 'Signes de poussée dentaire' },
        { p: 'Bave, envie de tout mâchouiller, irritabilité et sommeil moins bon sont typiques. Un anneau de dentition rafraîchi (pas congelé) et un massage des gencives avec un doigt propre peuvent soulager.' },
        { callout: { title: 'La fièvre n’est pas due aux dents', text: 'Une poussée dentaire peut faire monter légèrement la température, mais ne donne pas de fièvre dès 38 °C. Si bébé a de la fièvre, cherchez une autre cause et consultez un médecin. Seuils selon l’âge : <a href="/fr/guide/fievre-bebe-quand-consulter/">fièvre chez bébé</a>.' } },
        { h2: 'Première visite chez le dentiste' },
        { p: 'Prenez rendez-vous chez un dentiste pédiatrique dès la première dent, et au plus tard vers le premier anniversaire.' },
      ],
      sources: [
        'American Academy of Pediatric Dentistry, Dental Growth and Development',
        'American Academy of Pediatrics, Teething (healthychildren.org)',
      ],
      app: 'Dans l’onglet Dents, vous notez chaque dent avec sa date, et la courbe la compare aux repères habituels.',
      related: ['fever', 'sleep'],
    },
    {
      id: 'croup',
      published: '2026-09-29',
      slug: 'toux-aboyante-laryngite',
      emoji: '🐕',
      title: 'Toux aboyante la nuit : la laryngite chez l’enfant',
      metaTitle: 'Toux aboyante chez l’enfant (laryngite) : que faire et quand appeler le 15',
      description: 'Une toux qui aboie, une voix rauque et un bruit à l’inspiration. Comment reconnaître une laryngite, que faire la nuit et quand appeler le 15.',
      teaser: 'Que faire la nuit et quand appeler le 15.',
      basedOn: 'NHS, American Academy of Pediatrics',
      answer: 'Une toux aboyante et une voix rauque, souvent pires la nuit, sont typiques de la laryngite. Calmez l’enfant et gardez-le assis. Appelez le 15 en cas de bruit aigu à l’inspiration au repos, de peau qui se creuse entre les côtes, de lèvres bleues, ou si l’enfant bave et n’arrive pas à avaler.',
      blocks: [
        { h2: 'Reconnaître une laryngite' },
        { ul: [
          '<strong>Une toux qui aboie</strong>, comme un chien ou un phoque.',
          '<strong>Une voix rauque.</strong>',
          '<strong>Un bruit aigu à l’inspiration</strong>, souvent quand l’enfant pleure.',
          'Les symptômes sont souvent <strong>pires la nuit</strong> et durent quelques jours.',
        ] },
        { h2: 'Que faire' },
        { p: 'Calmez l’enfant et gardez-le assis ou droit : les pleurs et la peur aggravent la gêne respiratoire. En cas de fièvre ou de douleur, vous pouvez donner un antipyrétique selon la notice. Appelez le médecin, surtout si les symptômes ne passent pas.' },
        { h2: 'Urgence : appelez le 15' },
        { ol: [
          '<strong>Bruit aigu à l’inspiration même au repos</strong>, quand l’enfant est calme.',
          '<strong>La peau se creuse</strong> entre les côtes ou sous le sternum.',
          '<strong>Lèvres bleues</strong> ou peau très pâle, grisâtre.',
          '<strong>Il bave</strong> et n’arrive pas à avaler.',
          '<strong>Somnolence</strong>, l’enfant est épuisé par la respiration.',
        ] },
        { callout: { title: 'Pire la nuit, mieux le matin', text: 'La laryngite s’aggrave souvent la nuit et s’améliore le matin. S’il y a eu une gêne respiratoire la nuit, contactez le médecin même si l’enfant va mieux le matin. Autres signes urgents : <a href="/fr/guide/signes-d-alerte-bebe/">signes d’alerte chez bébé</a>.' } },
      ],
      sources: [
        'NHS, Croup (nhs.uk)',
        'American Academy of Pediatrics, Croup and Your Young Child (healthychildren.org)',
      ],
      app: 'Notez les épisodes de toux avec le moment de la journée et l’intensité, et l’appli vous alerte en cas de toux aboyante ou sifflante.',
      related: ['warning', 'fever'],
    },
    {
      id: 'solids',
      published: '2026-09-29',
      slug: 'quand-commencer-la-diversification',
      emoji: '🥕',
      title: 'Quand commencer la diversification ?',
      metaTitle: 'Quand commencer la diversification ? 4 signes que bébé est prêt',
      description: 'À partir de quand proposer des aliments solides à bébé, comment savoir s’il est prêt et ce qu’il faut éviter. D’après l’OMS, l’ESPGHAN et l’American Academy of Pediatrics.',
      teaser: 'Signes qu’il est prêt et ce qu’il faut éviter.',
      basedOn: 'OMS, ESPGHAN, American Academy of Pediatrics',
      answer: 'En général vers 6 mois, et jamais avant 4 mois. Bébé est prêt quand il tient assis avec appui, tient bien sa tête, s’intéresse aux repas et ne repousse plus la cuillère avec la langue. Pas de miel avant 12 mois.',
      blocks: [
        { h2: 'Signes qu’il est prêt' },
        { ol: [
          '<strong>Tient assis avec appui</strong> sans basculer.',
          '<strong>Tient bien sa tête.</strong>',
          '<strong>S’intéresse aux repas</strong>, tend la main, ouvre la bouche.',
          '<strong>Ne repousse plus la cuillère avec la langue.</strong>',
        ] },
        { h2: 'Comment commencer' },
        { ul: [
          'Introduisez les nouveaux aliments <strong>un par un, tous les 3-4 jours</strong> : une allergie se repère plus facilement.',
          'Le lait (maternel ou infantile) reste l’aliment principal la première année.',
          'Proposez des morceaux fondants ou des purées adaptés aux capacités de bébé.',
        ] },
        { h2: 'Ce qu’il faut éviter' },
        { table: {
          head: ['Aliment', 'À partir de', 'Pourquoi'],
          rows: [
            ['Miel', 'après 12 mois', 'Risque de botulisme', true],
            ['Fruits à coque entiers', 'après 5 ans', 'Risque d’étouffement', true],
            ['Lait de vache en boisson', 'après 12 mois', 'Trop peu de fer'],
          ],
        } },
        { callout: { title: 'Allergènes', text: 'Inutile de retarder les allergènes courants comme l’œuf ou le beurre de cacahuète lisse. En cas d’allergies alimentaires dans la famille, établissez un plan avec votre médecin.' } },
      ],
      sources: [
        'OMS, Alimentation de complément',
        'ESPGHAN, Complementary Feeding: A Position Paper (2017)',
        'American Academy of Pediatrics, Starting Solid Foods (healthychildren.org)',
      ],
      app: 'Dans l’onglet Diversification, vous notez les aliments déjà goûtés et les éventuelles réactions.',
      related: ['feeding', 'teeth'],
    },
  ],
}
