// Treść PL: strona aplikacji /spokojny-rodzic/ i poradnik /poradnik/.
// Dane medyczne z aplikacji (referenceTables.js, feedingNorms.js, sleepNorms.js).

export default {
  lang: 'pl',
  ogLocale: 'pl_PL',
  currency: 'PLN',
  appName: 'Spokojny Rodzic',
  appPath: '/spokojny-rodzic/',
  guidePath: '/poradnik/',
  ui: {
    navGuide: 'poradnik',
    navApp: 'aplikacja',
    guideName: 'Poradnik',
    cta: 'Pobierz z Google Play',
    answer: 'W skrócie',
    updated: 'Aktualizacja',
    date: '27 września 2026',
    basedOn: 'Na podstawie',
    sources: 'Źródła',
    related: 'Przeczytaj też',
    appSuffix: 'Bez reklam, 14 dni Premium za darmo.',
    articleDisclaimer: 'Ten artykuł ma charakter informacyjny i nie zastępuje porady lekarza. Gdy coś Cię niepokoi, skontaktuj się z lekarzem. W zagrożeniu życia dzwoń 112.',
    footer: 'Spokojny Rodzic · projekt <a href="/" style="color:var(--accent-dim);text-decoration:none;">skudev</a> · 2026',
    privacy: 'prywatność',
  },
  landing: {
    title: 'Spokojny Rodzic: dziennik niemowlaka dla obojga rodziców · Android',
    description: 'Karmienie, sen, pieluchy i gorączka jednym dotknięciem. Jedno Premium dla obojga rodziców, progi temperatury z wytycznych pediatrów, raport PDF na wizytę. Bez reklam. Aplikacja na Androida w Google Play.',
    eyebrow: '// Aplikacja dla rodziców · Android',
    h1: 'Dziennik niemowlaka <em>dla obojga</em> rodziców.',
    lead: 'Karmienie, sen, pieluchy i gorączka jednym dotknięciem. Oboje widzicie te same wpisy, każde na swoim telefonie. Progi temperatury z wytycznych pediatrów i raport PDF na wizytę. Bez reklam.',
    guideButton: 'Poradnik dla rodziców',
    status: 'w Google Play · polski, angielski, niemiecki, francuski, hiszpański',
    storyLabel: '// dlaczego ta apka',
    story: 'Nasze dziecko dostało gorączki w środku nocy. Szukałem w Google, co robić, i co strona, to inna odpowiedź. <em>Chciałem mieć wszystko w jednym miejscu</em>: pomiary, podane leki z godziną i progi z wytycznych pediatrów. Tak powstał Spokojny Rodzic.',
    storyAuthor: 'Mateusz, tata i twórca aplikacji',
    featuresLabel: '// co dostajesz',
    featuresTitle: 'Sześć rzeczy, których <em>brakowało</em> mi w innych apkach.',
    features: [
      { emoji: '🍼', title: 'Wpis jednym dotknięciem', text: 'Karmienie piersią lub butelką, sen i pieluchy. Z widżetu na ekranie głównym zapiszesz karmienie bez otwierania aplikacji.' },
      { emoji: '👨‍👩‍👧', title: 'Jedno Premium dla obojga', text: 'Zapraszasz partnera kodem i oboje widzicie te same wpisy na bieżąco. Płaci jedna osoba, Premium działa u obojga.' },
      { emoji: '🌡️', title: 'Temperatura z wykresem', text: 'Pomiary z godziną i trendem na wykresie. Obok progi referencyjne z wytycznych PTP i AAP, do przeczytania w każdej chwili.' },
      { emoji: '💊', title: 'Leki i przypomnienia', text: 'Zapisujesz, jaki lek i o której podano. Przypomnienie przychodzi na oba telefony. Aplikacja nie wylicza dawek, dawkę sprawdzasz w ulotce.' },
      { emoji: '📊', title: 'Siatki WHO i raport PDF', text: 'Waga, wzrost i obwód głowy na siatkach centylowych WHO. Raport PDF z wybranego okresu zabierasz na wizytę u pediatry.' },
      { emoji: '🔒', title: 'Bez reklam, dane w UE', text: 'Nie pokazuję reklam i nie sprzedaję danych. Dane są na serwerach w Unii Europejskiej, a eksport do CSV masz w każdej chwili.' },
    ],
    previewLabel: '// podgląd apki',
    previewTitle: 'Zbudowana, żeby <em>szybko wpisywać</em> jedną ręką.',
    phones: [
      { img: 'dzis', label: '01 · Dziś', title: 'Cały dzień na jednym ekranie', desc: 'Karmienia, sen, pieluchy i ostatnia temperatura.', alt: 'Ekran Dziś: karmienia, sen, pieluchy i ostatnia temperatura' },
      { img: 'karmienie', label: '02 · Karmienie', title: 'Karmienie w 2 sekundy', desc: 'Pierś, butelka i godzina jednym dotknięciem.', alt: 'Ekran karmienia: pierś lewa, pierś prawa, butelka' },
      { img: 'wspolne-konto', label: '03 · Wspólne konto', title: 'Jedno Premium dla obojga', desc: 'Te same wpisy na obu telefonach, na bieżąco.', alt: 'Wspólne konto: kod zaproszenia dla drugiego rodzica' },
    ],
    guidesLabel: '// poradnik',
    ctaLabel: '// pobierz',
    ctaTitle: '14 dni Premium <em>za darmo</em>, bez karty.',
    ctaLead: 'Po 14 dniach dalej używasz wersji podstawowej: zapis karmień, snu, temperatury i leków zostaje za darmo. Premium kupujesz tylko wtedy, gdy chcesz.',
    disclaimer: 'Spokojny Rodzic nie jest wyrobem medycznym. Nie diagnozuje, nie wylicza dawek leków i nie zastępuje lekarza. W zagrożeniu życia dzwoń 112.',
  },
  index: {
    title: 'Poradnik dla rodziców niemowląt',
    description: 'Gorączka, karmienie, pieluchy, sen i objawy alarmowe u niemowlęcia. Krótko i konkretnie, na podstawie wytycznych pediatrów.',
    eyebrow: '// Poradnik dla rodziców',
    h1: 'Krótko i konkretnie, <em>z wytycznych</em> pediatrów.',
    lead: 'Odpowiedzi na pytania, które rodzice niemowląt zadają najczęściej, często w środku nocy. Każdy artykuł podaje źródła.',
    disclaimer: 'Poradnik ma charakter informacyjny i nie zastępuje porady lekarza. W zagrożeniu życia dzwoń 112.',
  },
  articles: [
    {
      id: 'fever',
      slug: 'goraczka-u-niemowlaka-kiedy-do-lekarza',
      emoji: '🌡️',
      title: 'Gorączka u niemowlaka: kiedy do lekarza?',
      metaTitle: 'Gorączka u niemowlaka: kiedy do lekarza? Progi według wieku',
      description: 'Od jakiej temperatury z niemowlęciem jechać do lekarza? Progi gorączki według wieku dziecka na podstawie wytycznych Polskiego Towarzystwa Pediatrycznego i AAP.',
      teaser: 'Progi temperatury według wieku dziecka.',
      basedOn: 'KOMPAS GORĄCZKA (Polskie Towarzystwo Pediatryczne), American Academy of Pediatrics',
      answer: 'U niemowlęcia poniżej 3 miesięcy każda temperatura od 38,0°C to powód do pilnej wizyty u lekarza, także w nocy. Od 3. do 6. miesiąca przy 38,0°C skontaktuj się z pediatrą. U starszych dzieci progiem konsultacji jest 39,0°C, a od 40,5°C w każdym wieku potrzebna jest pilna pomoc.',
      blocks: [
        { h2: 'Progi gorączki według wieku' },
        { table: {
          head: ['Wiek dziecka', 'Temperatura', 'Co zrobić'],
          rows: [
            ['Poniżej 3 miesięcy', 'od 38,0°C', 'Pilnie do lekarza, nawet w nocy', true],
            ['3 do 6 miesięcy', 'od 38,0°C', 'Skontaktuj się z pediatrą'],
            ['Powyżej 6 miesięcy', '38,5 do 39,0°C', 'Wysoka gorączka. Lek przeciwgorączkowy może poprawić komfort dziecka, dawka według ulotki'],
            ['Powyżej 6 miesięcy', 'od 39,0°C', 'Skontaktuj się z pediatrą'],
            ['W każdym wieku', 'od 40,5°C', 'Pilna pomoc lekarska', true],
          ],
        } },
        { h2: 'Dlaczego u najmłodszych próg jest niższy?' },
        { p: 'W pierwszych 3 miesiącach życia odporność dziecka jest jeszcze niedojrzała, a gorączka bywa jedynym objawem poważnej infekcji. Dlatego wytyczne zalecają pilną ocenę lekarską nawet wtedy, gdy niemowlę poza temperaturą wygląda dobrze.' },
        { h2: 'Gorączka trwa dłużej niż 3 doby' },
        { p: 'Jeśli u dziecka powyżej 6 miesięcy gorączka utrzymuje się ponad 72 godziny, skontaktuj się z pediatrą, nawet gdy dziecko czuje się nieźle.' },
        { callout: { title: 'Nie patrz tylko na termometr', text: 'Apatia, trudność z wybudzeniem, trudności w oddychaniu, drgawki albo plamy, które nie bledną przy ucisku, wymagają pilnej pomocy niezależnie od temperatury. Pełna lista: <a href="/poradnik/objawy-alarmowe-u-dziecka/">objawy alarmowe u dziecka</a>.' } },
        { h2: 'Zapisuj pomiary z godziną' },
        { p: 'Lekarz zapyta, od kiedy trwa gorączka, jak wysoka była i kiedy podano lek. Jeśli zapisujesz pomiary z godziną, łatwiej odpowiedzieć i łatwiej zauważyć, czy temperatura rośnie, czy spada.' },
      ],
      sources: [
        'KOMPAS GORĄCZKA, rekomendacje Polskiego Towarzystwa Pediatrycznego',
        'American Academy of Pediatrics, Clinical Practice Guideline: Evaluation and Management of Well-Appearing Febrile Infants 8 to 60 Days Old (2021)',
      ],
      app: 'Pomiary temperatury z wykresem, podane leki z godziną i te progi masz w jednym miejscu, także na telefonie drugiego rodzica.',
      related: ['warning', 'diapers'],
    },
    {
      id: 'warning',
      slug: 'objawy-alarmowe-u-dziecka',
      emoji: '🚨',
      title: 'Objawy alarmowe u dziecka: kiedy nie czekać do rana',
      metaTitle: 'Objawy alarmowe u dziecka: kiedy na SOR lub pod 112',
      description: 'Przy jakich objawach z dzieckiem jechać na SOR albo dzwonić pod 112, a kiedy wystarczy kontakt z pediatrą. Lista na podstawie wytycznych PTP i AAP.',
      teaser: 'Kiedy jechać na SOR albo dzwonić pod 112.',
      basedOn: 'KOMPAS GORĄCZKA (Polskie Towarzystwo Pediatryczne), American Academy of Pediatrics',
      answer: 'Nie czekaj do rana, gdy niemowlę poniżej 3 miesięcy ma gorączkę od 38°C, gdy dziecko jest apatyczne i trudno je wybudzić, ma trudności w oddychaniu lub sine usta, drgawki, sztywny kark albo plamy, które nie bledną przy ucisku. Wtedy potrzebna jest pilna pomoc: SOR lub numer 112.',
      blocks: [
        { h2: 'Pilnie: SOR lub 112' },
        { ol: [
          '<strong>Gorączka od 38°C u niemowlęcia poniżej 3 miesięcy</strong>, nawet bez innych objawów.',
          '<strong>Temperatura od 40,5°C</strong> w każdym wieku.',
          '<strong>Apatia, trudność z wybudzeniem, brak reakcji</strong> na głos i dotyk.',
          '<strong>Trudności w oddychaniu</strong>, świszczący oddech, sine usta.',
          '<strong>Drgawki, sztywność karku</strong> albo <strong>plamy, które nie bledną przy ucisku</strong>.',
        ] },
        { h2: 'Jak sprawdzić, czy plamy bledną?' },
        { p: 'Przyłóż do wysypki przezroczystą szklankę i lekko dociśnij. Jeśli plamy są nadal wyraźnie widoczne przez szkło, nie czekaj: to objaw, który wymaga pilnej pomocy.' },
        { h2: 'Skontaktuj się z lekarzem' },
        { ul: [
          '<strong>Oznaki odwodnienia:</strong> sucha pielucha ponad 6 godzin, płacz bez łez, zapadnięte ciemiączko.',
          '<strong>Uporczywe wymioty lub biegunka</strong> trwająca ponad dobę u niemowlęcia.',
          '<strong>Gorączka ponad 72 godziny</strong> u dziecka powyżej 6 miesięcy.',
        ] },
        { callout: { title: 'Numery', text: '<strong>112</strong> to numer alarmowy w całej Unii Europejskiej. W sprawach mniej pilnych w nocy i w święta pomoże nocna i świąteczna opieka zdrowotna. Adres najbliższej placówki podaje Telefoniczna Informacja Pacjenta NFZ: <strong>800 190 590</strong>.' } },
        { p: 'Masz wątpliwości? Lepiej sprawdzić o jeden raz za dużo. Progi temperatury według wieku znajdziesz w artykule <a href="/poradnik/goraczka-u-niemowlaka-kiedy-do-lekarza/">gorączka u niemowlaka: kiedy do lekarza</a>.' },
      ],
      sources: [
        'KOMPAS GORĄCZKA, rekomendacje Polskiego Towarzystwa Pediatrycznego',
        'American Academy of Pediatrics',
        'Medycyna Praktyczna, pediatria',
      ],
      app: 'Lista objawów alarmowych i numer 112 są w aplikacji zawsze pod ręką, razem z historią pomiarów, którą pokażesz lekarzowi.',
      related: ['fever', 'diapers'],
    },
    {
      id: 'feeding',
      slug: 'ile-razy-je-niemowle',
      emoji: '🍼',
      title: 'Ile razy na dobę je niemowlę?',
      metaTitle: 'Ile razy na dobę je niemowlę? Liczba karmień według wieku',
      description: 'Ile karmień na dobę to typowo u noworodka, 3-miesięcznego i rocznego dziecka? Zakresy według American Academy of Pediatrics, WHO i ESPGHAN.',
      teaser: 'Typowa liczba karmień od noworodka do roczniaka.',
      basedOn: 'American Academy of Pediatrics, WHO, ESPGHAN',
      answer: 'Noworodek w pierwszym miesiącu je zwykle 8 do 12 razy na dobę, czyli mniej więcej co 2 do 3 godzin. Z wiekiem karmień jest mniej: w 4. do 6. miesiącu zwykle 5 do 7, a pod koniec pierwszego roku 4 do 6 na dobę.',
      blocks: [
        { h2: 'Liczba karmień mlekiem na dobę' },
        { table: {
          head: ['Wiek dziecka', 'Karmienia na dobę'],
          rows: [
            ['0 do 1 miesiąca', '8 do 12'],
            ['2 do 3 miesięcy', '7 do 9'],
            ['4 do 6 miesięcy', '5 do 7'],
            ['7 do 12 miesięcy', '4 do 6'],
            ['1 do 2 lat', '3 do 5'],
          ],
        } },
        { p: 'Liczymy karmienia mlekiem (pierś i butelka), bez posiłków stałych.' },
        { h2: 'To zakresy, nie norma' },
        { p: 'Karmienie na żądanie to standard według American Academy of Pediatrics i WHO. Liczba karmień zmienia się z dnia na dzień, na przykład przy skokach rozwojowych. Ważniejsze od samej liczby jest to, czy dziecko przybiera na wadze i moczy pieluchy. Jak to sprawdzić, piszemy w artykule <a href="/poradnik/ile-mokrych-pieluch/">ile mokrych pieluch to dobry znak</a>.' },
        { h2: 'Kiedy porozmawiać z pediatrą' },
        { p: 'Gdy masz wątpliwości co do przyrostu wagi albo dziecko moczy mniej pieluch niż zwykle, porozmawiaj z pediatrą lub doradcą laktacyjnym.' },
      ],
      sources: [
        'American Academy of Pediatrics, Breastfeeding and the Use of Human Milk (2022)',
        'WHO, Infant and young child feeding (2021)',
        'ESPGHAN, Complementary Feeding: A Position Paper (2017)',
      ],
      app: 'Karmienie piersią lub butelką zapiszesz jednym dotknięciem, a aplikacja policzy karmienia z całego dnia i pokaże, ile minęło od ostatniego.',
      related: ['diapers', 'sleep'],
    },
    {
      id: 'diapers',
      slug: 'ile-mokrych-pieluch',
      emoji: '💧',
      title: 'Ile mokrych pieluch na dobę to dobry znak?',
      metaTitle: 'Ile mokrych pieluch na dobę? Jak rozpoznać odwodnienie u niemowlęcia',
      description: 'Ile mokrych pieluch na dobę powinno mieć niemowlę i jakie są sygnały odwodnienia? Prosty sposób, by sprawdzić, czy maluch pije dość.',
      teaser: 'Prosty sposób, by sprawdzić, czy maluch nie jest odwodniony.',
      basedOn: 'American Academy of Pediatrics, Polskie Towarzystwo Pediatryczne',
      answer: 'Od około 5. doby życia niemowlę moczy zwykle co najmniej 6 pieluch na dobę. Mniej mokrych pieluch, sucha pielucha przez ponad 6 godzin, płacz bez łez albo zapadnięte ciemiączko mogą oznaczać odwodnienie i są powodem do kontaktu z lekarzem.',
      blocks: [
        { h2: 'Pierwsze dni po porodzie' },
        { p: 'W pierwszych dniach mokrych pieluch jest mniej, bo pokarmu jest jeszcze niewiele. Ich liczba rośnie z każdym dniem, a od około 5. doby powinno ich być co najmniej 6 na dobę.' },
        { h2: 'Sygnały odwodnienia' },
        { ul: [
          'Sucha pielucha przez ponad 6 godzin',
          'Płacz bez łez',
          'Zapadnięte ciemiączko',
          'Mniej niż 6 mokrych pieluch na dobę',
        ] },
        { callout: { title: 'Kiedy do lekarza', text: 'Przy oznakach odwodnienia skontaktuj się z lekarzem, szczególnie u niemowlęcia. Uporczywe wymioty albo biegunka trwająca ponad dobę u niemowlęcia też są powodem do konsultacji, bo szybko prowadzą do odwodnienia.' } },
        { h2: 'Jak liczyć pieluchy w nocy' },
        { p: 'Po kilku nieprzespanych nocach trudno pamiętać, ile pieluch było od rana. Zapisuj każdą zmianę od razu, wtedy wystarczy rzut oka, żeby wiedzieć, czy dziś było ich dość.' },
      ],
      sources: [
        'American Academy of Pediatrics',
        'Polskie Towarzystwo Pediatryczne',
      ],
      app: 'Mokre i brudne pieluchy zapiszesz jednym dotknięciem, a licznik z całego dnia widzisz od razu na ekranie głównym.',
      related: ['feeding', 'warning'],
    },
    {
      id: 'sleep',
      slug: 'ile-spi-niemowle',
      emoji: '😴',
      title: 'Ile powinno spać niemowlę?',
      metaTitle: 'Ile powinno spać niemowlę? Sen na dobę według wieku',
      description: 'Ile godzin na dobę śpi noworodek, 4-miesięczne niemowlę i roczne dziecko? Zakresy snu według National Sleep Foundation i American Academy of Pediatrics.',
      teaser: 'Sen na dobę według wieku, razem z drzemkami.',
      basedOn: 'National Sleep Foundation, American Academy of Pediatrics',
      answer: 'Niemowlę do 3. miesiąca śpi łącznie 14 do 17 godzin na dobę, od 4. do 11. miesiąca 12 do 15 godzin, a dziecko w wieku 1 do 2 lat 11 do 14 godzin, razem z drzemkami.',
      blocks: [
        { h2: 'Sen na dobę według wieku' },
        { table: {
          head: ['Wiek dziecka', 'Sen na dobę'],
          rows: [
            ['0 do 3 miesięcy', '14 do 17 godzin'],
            ['4 do 11 miesięcy', '12 do 15 godzin'],
            ['1 do 2 lat', '11 do 14 godzin'],
            ['3 do 5 lat', '10 do 13 godzin'],
          ],
        } },
        { p: 'To zakresy dla całej doby, razem z drzemkami. Każde dziecko śpi inaczej, więc to punkt odniesienia, a nie norma.' },
        { h2: 'Noworodek budzi się często' },
        { p: 'Noworodek śpi w krótkich odcinkach i budzi się co 1 do 3 godzin, głównie na karmienie. Rytm dnia i nocy układa się zwykle w ciągu pierwszych 2 miesięcy. Pomaga jasny dzień i ciemna, cicha noc.' },
        { h2: 'Gorszy sen około 4. miesiąca' },
        { p: 'Około 4. miesiąca sen często na jakiś czas się pogarsza. To naturalny etap rozwoju mózgu, a nie błąd rodziców.' },
      ],
      sources: [
        'National Sleep Foundation, Sleep Time Duration Recommendations (2015)',
        'American Academy of Pediatrics, Recommended Amount of Sleep for Pediatric Populations (2016)',
      ],
      app: 'Start i koniec snu zapisujesz jednym dotknięciem, a aplikacja sama zsumuje sen i drzemki z całego dnia.',
      related: ['feeding', 'fever'],
    },
  ],
}
