// Ciąża (3 paź 2026): kalkulator terminu porodu i artykuły ciążowe w 5 językach.
// build-site.mjs dokleja te artykuły (section: 'pregnancy') przed artykuły
// o niemowlęciu i buduje strony narzędzi (tools) w ścieżce poradnika.
//
// Francja liczy termin na 41 SA (287 dni, CNGOF), reszta na 40 tygodni (280 dni),
// tak samo jak aplikacja (termDaysForLocale w babylog/src/utils/pregnancy.js).

const dueDate = {
  pl: {
    id: 'dueDate',
    slug: 'kalkulator-terminu-porodu',
    emoji: '📅',
    title: 'Kalkulator terminu porodu i tygodnia ciąży',
    metaTitle: 'Kalkulator terminu porodu: który to tydzień ciąży?',
    description: 'Policz termin porodu z daty ostatniej miesiączki, daty poczęcia albo terminu z USG. Zobaczysz tydzień ciąży, trymestr i ile dni zostało do porodu.',
    teaser: 'Termin, tydzień i trymestr w kilka sekund.',
    basedOn: 'ACOG, WHO',
    answer: 'Termin porodu to 280 dni (40 tygodni) od pierwszego dnia ostatniej miesiączki. Wpisz datę, a kalkulator pokaże termin, obecny tydzień ciąży, trymestr i najważniejsze daty.',
    termDays: 280,
    form: {
      method: 'Licz na podstawie',
      methods: { lmp: 'ostatniej miesiączki', conception: 'daty poczęcia', due: 'terminu z USG' },
      dateLabels: { lmp: 'Pierwszy dzień ostatniej miesiączki', conception: 'Data poczęcia', due: 'Termin porodu z USG' },
      cycle: 'Długość cyklu (dni)',
      cycleHint: 'Zwykle 28. Przy dłuższym cyklu termin przesuwa się o tyle dni, o ile cykl jest dłuższy.',
      button: 'Policz termin',
    },
    result: {
      due: 'Termin porodu',
      week: 'Tydzień ciąży',
      trimester: 'Trymestr',
      left: 'Do terminu',
      milestones: 'Ważne daty',
      ms: {
        t1: 'Koniec 1. trymestru (13+6)',
        t2: 'Koniec 2. trymestru (27+6)',
        term: 'Ciąża donoszona od (37+0)',
        due: 'Termin porodu (40+0)',
        post: 'Ukończone 42 tygodnie (42+0)',
      },
      saveTitle: 'Zapisz termin w aplikacji',
      saveText: 'Spokojny Rodzic liczy tydzień ciąży każdego dnia i ma licznik skurczy. Po porodzie jednym przyciskiem przechodzi w dziennik niemowlaka.',
    },
    fmt: {
      weekBig: '{week}. tydzień ciąży',
      weekSmall: '{w}+{d}',
      trimester: '{n}. trymestr',
      days: ['{n} dzień', '{n} dni'],
      overdue: ['Termin minął {n} dzień temu', 'Termin minął {n} dni temu'],
      today: 'Termin jest dziś',
    },
    errors: {
      empty: 'Wybierz datę.',
      range: 'Ta data nie pasuje do trwającej ciąży. Sprawdź, czy wpisujesz dobrą datę.',
    },
    blocks: [
      { h2: 'Jak liczy się termin porodu' },
      { p: 'Lekarze liczą ciążę od pierwszego dnia ostatniej miesiączki, a nie od poczęcia. Termin to ten dzień plus 280 dni, czyli 40 tygodni (reguła Naegelego). Przy cyklu dłuższym albo krótszym niż 28 dni termin przesuwa się o różnicę.' },
      { h2: 'Termin z USG jest dokładniejszy' },
      { p: 'Najdokładniej termin wyznacza USG w pierwszym trymestrze. Jeśli lekarz ustalił termin na podstawie USG, wybierz „terminu z USG”: kalkulator policzy z niego tydzień ciąży.' },
      { h2: 'Dokładnie w terminie rodzi się niewiele dzieci' },
      { p: 'Termin to przybliżenie. Ciąża jest donoszona od 37. tygodnia, a poród między ukończonym 37. a 42. tygodniem to poród o czasie. Dlatego warto mieć spakowaną torbę już około 36. tygodnia.' },
    ],
    faq: [
      { q: 'Od kiedy liczy się tydzień ciąży?', a: 'Od pierwszego dnia ostatniej miesiączki. Dlatego w chwili poczęcia jesteś już mniej więcej w 3. tygodniu ciąży.' },
      { q: 'Co znaczy zapis 24+3?', a: '24 pełne tygodnie i 3 dni. Trwa wtedy 25. tydzień ciąży.' },
      { q: 'Ile trwają trymestry?', a: 'Pierwszy do końca 13. tygodnia (13+6), drugi do końca 27. tygodnia (27+6), trzeci od 28. tygodnia do porodu.' },
    ],
    sources: [
      'ACOG Committee Opinion No. 700: Methods for Estimating the Due Date (2017)',
      'WHO: Preterm birth, definicje porodu przedwczesnego i o czasie (2023)',
    ],
    related: ['bag', 'labor'],
  },
  en: {
    id: 'dueDate',
    slug: 'due-date-calculator',
    emoji: '📅',
    title: 'Due date and pregnancy week calculator',
    metaTitle: 'Due date calculator: how many weeks pregnant am I?',
    description: 'Work out your due date from your last period, conception date or ultrasound due date. See your pregnancy week, trimester and how many days are left.',
    teaser: 'Due date, week and trimester in seconds.',
    basedOn: 'ACOG, WHO',
    answer: 'Your due date is 280 days (40 weeks) after the first day of your last period. Enter a date and the calculator shows your due date, current pregnancy week, trimester and key dates.',
    termDays: 280,
    form: {
      method: 'Calculate from',
      methods: { lmp: 'last period', conception: 'conception date', due: 'ultrasound due date' },
      dateLabels: { lmp: 'First day of your last period', conception: 'Conception date', due: 'Due date from ultrasound' },
      cycle: 'Cycle length (days)',
      cycleHint: 'Usually 28. With a longer cycle, the due date moves later by the extra days.',
      button: 'Calculate',
    },
    result: {
      due: 'Due date',
      week: 'Pregnancy week',
      trimester: 'Trimester',
      left: 'Until due date',
      milestones: 'Key dates',
      ms: {
        t1: 'End of 1st trimester (13w 6d)',
        t2: 'End of 2nd trimester (27w 6d)',
        term: 'Full term from (37w 0d)',
        due: 'Due date (40w 0d)',
        post: '42 weeks (42w 0d)',
      },
      saveTitle: 'Save your due date in the app',
      saveText: 'Calm Parent counts your pregnancy week every day and has a contraction timer. After the birth, one tap turns it into a baby log.',
    },
    fmt: {
      weekBig: 'Week {week}',
      weekSmall: '{w}w {d}d',
      trimester: ['1st trimester', '2nd trimester', '3rd trimester'],
      days: ['{n} day', '{n} days'],
      overdue: ['{n} day past the due date', '{n} days past the due date'],
      today: 'Your due date is today',
    },
    errors: {
      empty: 'Choose a date.',
      range: 'This date doesn’t match an ongoing pregnancy. Please check it.',
    },
    blocks: [
      { h2: 'How the due date is calculated' },
      { p: 'Doctors count pregnancy from the first day of your last period, not from conception. The due date is that day plus 280 days, or 40 weeks (Naegele’s rule). If your cycle is longer or shorter than 28 days, the due date moves by the difference.' },
      { h2: 'An ultrasound due date is more accurate' },
      { p: 'An ultrasound in the first trimester gives the most accurate due date. If your doctor set your due date from a scan, choose “ultrasound due date” and the calculator will work out your pregnancy week from it.' },
      { h2: 'Few babies arrive exactly on the due date' },
      { p: 'The due date is an estimate. A pregnancy is full term from 37 weeks, and a birth between 37 and 42 completed weeks counts as on time. That’s why it’s worth having your hospital bag ready by about 36 weeks.' },
    ],
    faq: [
      { q: 'When does pregnancy week counting start?', a: 'From the first day of your last period. That’s why at conception you are already about 3 weeks pregnant.' },
      { q: 'What does 24w 3d mean?', a: '24 full weeks and 3 days. You are then in week 25 of pregnancy.' },
      { q: 'How long is each trimester?', a: 'The first trimester lasts until the end of week 13 (13w 6d), the second until the end of week 27 (27w 6d), and the third from week 28 until birth.' },
    ],
    sources: [
      'ACOG Committee Opinion No. 700: Methods for Estimating the Due Date (2017)',
      'WHO: Preterm birth, definitions of preterm and term birth (2023)',
    ],
    related: ['bag', 'labor'],
  },
  de: {
    id: 'dueDate',
    slug: 'geburtstermin-rechner',
    emoji: '📅',
    title: 'Geburtstermin-Rechner und Schwangerschaftswoche',
    metaTitle: 'Geburtstermin berechnen: in welcher SSW bin ich?',
    description: 'Berechnen Sie den Geburtstermin aus der letzten Periode, dem Empfängnisdatum oder dem Termin aus dem Ultraschall. Mit SSW, Trimester und Tagen bis zur Geburt.',
    teaser: 'Termin, SSW und Trimester in Sekunden.',
    basedOn: 'ACOG, WHO',
    answer: 'Der Geburtstermin liegt 280 Tage (40 Wochen) nach dem ersten Tag der letzten Periode. Geben Sie ein Datum ein, und der Rechner zeigt den Termin, die aktuelle Schwangerschaftswoche, das Trimester und wichtige Daten.',
    termDays: 280,
    form: {
      method: 'Berechnen nach',
      methods: { lmp: 'letzter Periode', conception: 'Empfängnisdatum', due: 'Termin aus dem Ultraschall' },
      dateLabels: { lmp: 'Erster Tag der letzten Periode', conception: 'Empfängnisdatum', due: 'Geburtstermin laut Ultraschall' },
      cycle: 'Zykluslänge (Tage)',
      cycleHint: 'Meist 28. Bei einem längeren Zyklus verschiebt sich der Termin um die zusätzlichen Tage nach hinten.',
      button: 'Termin berechnen',
    },
    result: {
      due: 'Geburtstermin',
      week: 'Schwangerschaftswoche',
      trimester: 'Trimester',
      left: 'Bis zum Termin',
      milestones: 'Wichtige Daten',
      ms: {
        t1: 'Ende 1. Trimester (13+6)',
        t2: 'Ende 2. Trimester (27+6)',
        term: 'Reifes Kind ab (37+0)',
        due: 'Geburtstermin (40+0)',
        post: '42 vollendete Wochen (42+0)',
      },
      saveTitle: 'Termin in der App speichern',
      saveText: 'Calm Parent zählt die Schwangerschaftswoche jeden Tag und hat einen Wehen-Timer. Nach der Geburt wird daraus mit einem Tipp ein Baby-Tagebuch.',
    },
    fmt: {
      weekBig: '{week}. SSW',
      weekSmall: '{w}+{d}',
      trimester: '{n}. Trimester',
      days: ['{n} Tag', '{n} Tage'],
      overdue: ['{n} Tag nach dem Termin', '{n} Tage nach dem Termin'],
      today: 'Heute ist der Geburtstermin',
    },
    errors: {
      empty: 'Bitte ein Datum auswählen.',
      range: 'Dieses Datum passt nicht zu einer laufenden Schwangerschaft. Bitte prüfen.',
    },
    blocks: [
      { h2: 'So wird der Geburtstermin berechnet' },
      { p: 'Ärztinnen und Ärzte zählen die Schwangerschaft ab dem ersten Tag der letzten Periode, nicht ab der Empfängnis. Der Termin ist dieser Tag plus 280 Tage, also 40 Wochen (Naegele-Regel). Ist der Zyklus länger oder kürzer als 28 Tage, verschiebt sich der Termin um die Differenz.' },
      { h2: 'Der Termin aus dem Ultraschall ist genauer' },
      { p: 'Am genauesten bestimmt ein Ultraschall im ersten Trimester den Termin. Steht Ihr Termin laut Ultraschall im Mutterpass, wählen Sie „Termin aus dem Ultraschall“: Der Rechner bestimmt daraus die Schwangerschaftswoche.' },
      { h2: 'Nur wenige Kinder kommen genau am Termin' },
      { p: 'Der Termin ist eine Schätzung. Ab 37 Wochen gilt ein Kind als reif, eine Geburt zwischen vollendeter 37. und 42. Woche ist termingerecht. Packen Sie die Kliniktasche deshalb schon um die 36. Woche.' },
    ],
    faq: [
      { q: 'Ab wann zählt die Schwangerschaftswoche?', a: 'Ab dem ersten Tag der letzten Periode. Deshalb sind Sie bei der Empfängnis bereits etwa in der 3. SSW.' },
      { q: 'Was bedeutet 24+3?', a: '24 vollendete Wochen und 3 Tage. Sie sind dann in der 25. SSW.' },
      { q: 'Wie lange dauern die Trimester?', a: 'Das erste Trimester bis zum Ende der 13. Woche (13+6), das zweite bis zum Ende der 27. Woche (27+6), das dritte ab der 28. Woche bis zur Geburt.' },
    ],
    sources: [
      'ACOG Committee Opinion No. 700: Methods for Estimating the Due Date (2017)',
      'WHO: Preterm birth, Definitionen von Früh- und Termingeburt (2023)',
    ],
    related: ['bag', 'labor'],
  },
  fr: {
    id: 'dueDate',
    slug: 'calcul-date-accouchement',
    emoji: '📅',
    title: 'Calcul de la date d’accouchement et de la semaine de grossesse',
    metaTitle: 'Calculer sa date d’accouchement : à combien de SA suis-je ?',
    description: 'Calculez la date prévue d’accouchement à partir des dernières règles, de la date de conception ou du terme de l’échographie. Avec les SA, le trimestre et les jours restants.',
    teaser: 'Terme, SA et trimestre en quelques secondes.',
    basedOn: 'CNGOF, ACOG, OMS',
    answer: 'En France, la date prévue d’accouchement est fixée à 41 semaines d’aménorrhée (SA), soit 287 jours après le premier jour des dernières règles. Entrez une date : le calculateur affiche le terme, les SA, le trimestre et les dates clés.',
    termDays: 287,
    // Granice trymestrów we Francji liczy się inaczej: bez nich, tylko daty w SA.
    milestones: ['term', 'due', 'post'],
    form: {
      method: 'Calculer à partir',
      methods: { lmp: 'des dernières règles', conception: 'de la date de conception', due: 'du terme de l’échographie' },
      dateLabels: { lmp: 'Premier jour des dernières règles', conception: 'Date de conception', due: 'Date prévue selon l’échographie' },
      cycle: 'Durée du cycle (jours)',
      cycleHint: 'Souvent 28. Avec un cycle plus long, le terme recule d’autant de jours.',
      button: 'Calculer',
    },
    result: {
      due: 'Date prévue d’accouchement',
      week: 'Âge de la grossesse',
      trimester: 'Trimestre',
      left: 'Avant le terme',
      milestones: 'Dates clés',
      ms: {
        t1: 'Fin du 1er trimestre',
        t2: 'Fin du 2e trimestre',
        term: 'Grossesse à terme (37 SA)',
        due: 'Date prévue d’accouchement (41 SA)',
        post: 'Terme dépassé (42 SA)',
      },
      saveTitle: 'Enregistrer le terme dans l’appli',
      saveText: 'Calm Parent compte les SA chaque jour et propose un minuteur de contractions. Après la naissance, un seul bouton le transforme en carnet de bébé.',
    },
    fmt: {
      weekBig: '{w} SA + {d} j',
      weekSmall: '{week}e semaine d’aménorrhée',
      trimester: ['1er trimestre', '2e trimestre', '3e trimestre'],
      days: ['{n} jour', '{n} jours'],
      overdue: ['{n} jour après le terme', '{n} jours après le terme'],
      today: 'C’est la date prévue aujourd’hui',
    },
    errors: {
      empty: 'Choisissez une date.',
      range: 'Cette date ne correspond pas à une grossesse en cours. Vérifiez-la.',
    },
    blocks: [
      { h2: 'Comment le terme est calculé' },
      { p: 'Les médecins comptent la grossesse en semaines d’aménorrhée (SA), à partir du premier jour des dernières règles. En France, le terme est fixé à 41 SA, soit 287 jours. Dans beaucoup d’autres pays, on le fixe à 40 SA (280 jours) : ne vous étonnez pas si une appli étrangère donne une date une semaine plus tôt.' },
      { h2: 'Le terme de l’échographie est plus précis' },
      { p: 'L’échographie de datation du premier trimestre donne le terme le plus fiable. Si votre terme a été fixé à l’échographie, choisissez « du terme de l’échographie » : le calculateur en déduit les SA.' },
      { h2: 'Peu de bébés naissent le jour du terme' },
      { p: 'Le terme est une estimation. La grossesse est à terme dès 37 SA, et une naissance entre 37 et 42 SA est considérée comme à terme. Préparez donc votre valise de maternité vers 36 SA.' },
    ],
    faq: [
      { q: 'Quelle différence entre SA et SG ?', a: 'Les SA comptent depuis les dernières règles, les semaines de grossesse (SG) depuis la conception. SA = SG + 2.' },
      { q: 'Que signifie 24 SA + 3 j ?', a: '24 semaines complètes et 3 jours depuis les dernières règles : vous êtes dans la 25e semaine d’aménorrhée.' },
      { q: 'Pourquoi 41 SA en France ?', a: 'C’est la convention française du CNGOF. Au-delà de 41 SA, l’équipe médicale renforce la surveillance ; le terme est dépassé à 42 SA.' },
    ],
    sources: [
      'CNGOF : grossesse prolongée et terme dépassé, recommandations pour la pratique clinique',
      'ACOG Committee Opinion No. 700 : Methods for Estimating the Due Date (2017)',
      'OMS : naissances prématurées, définitions (2023)',
    ],
    related: ['bag', 'labor'],
  },
  es: {
    id: 'dueDate',
    slug: 'calculadora-fecha-de-parto',
    emoji: '📅',
    title: 'Calculadora de fecha de parto y semana de embarazo',
    metaTitle: 'Calculadora de fecha de parto: ¿de cuántas semanas estoy?',
    description: 'Calcula la fecha probable de parto a partir de la última regla, la fecha de concepción o la fecha de la ecografía. Con la semana de embarazo, el trimestre y los días que faltan.',
    teaser: 'Fecha, semana y trimestre en segundos.',
    basedOn: 'ACOG, OMS',
    answer: 'La fecha probable de parto es 280 días (40 semanas) después del primer día de la última regla. Introduce una fecha y la calculadora te muestra la fecha de parto, la semana de embarazo, el trimestre y las fechas clave.',
    termDays: 280,
    form: {
      method: 'Calcular a partir de',
      methods: { lmp: 'la última regla', conception: 'la fecha de concepción', due: 'la fecha de la ecografía' },
      dateLabels: { lmp: 'Primer día de la última regla', conception: 'Fecha de concepción', due: 'Fecha probable de parto según la ecografía' },
      cycle: 'Duración del ciclo (días)',
      cycleHint: 'Normalmente 28. Con un ciclo más largo, la fecha se retrasa tantos días como sea más largo.',
      button: 'Calcular',
    },
    result: {
      due: 'Fecha probable de parto',
      week: 'Semana de embarazo',
      trimester: 'Trimestre',
      left: 'Hasta la fecha',
      milestones: 'Fechas clave',
      ms: {
        t1: 'Fin del primer trimestre (13+6)',
        t2: 'Fin del segundo trimestre (27+6)',
        term: 'Embarazo a término desde (37+0)',
        due: 'Fecha probable de parto (40+0)',
        post: '42 semanas cumplidas (42+0)',
      },
      saveTitle: 'Guarda la fecha en la app',
      saveText: 'Calm Parent cuenta la semana de embarazo cada día y tiene un contador de contracciones. Después del parto, con un toque se convierte en un diario del bebé.',
    },
    fmt: {
      weekBig: 'Semana {week}',
      weekSmall: '{w}+{d}',
      trimester: ['Primer trimestre', 'Segundo trimestre', 'Tercer trimestre'],
      days: ['{n} día', '{n} días'],
      overdue: ['{n} día después de la fecha', '{n} días después de la fecha'],
      today: 'Hoy es la fecha probable de parto',
    },
    errors: {
      empty: 'Elige una fecha.',
      range: 'Esta fecha no corresponde a un embarazo en curso. Revísala.',
    },
    blocks: [
      { h2: 'Cómo se calcula la fecha de parto' },
      { p: 'Los médicos cuentan el embarazo desde el primer día de la última regla, no desde la concepción. La fecha probable de parto es ese día más 280 días, es decir, 40 semanas (regla de Naegele). Si tu ciclo es más largo o más corto de 28 días, la fecha se desplaza la diferencia.' },
      { h2: 'La fecha de la ecografía es más precisa' },
      { p: 'La ecografía del primer trimestre es la que mejor fija la fecha de parto. Si tu médico la calculó con una ecografía, elige «la fecha de la ecografía» y la calculadora sacará de ella la semana de embarazo.' },
      { h2: 'Pocos bebés nacen justo en la fecha' },
      { p: 'La fecha es una estimación. El embarazo es a término desde la semana 37, y un parto entre las 37 y las 42 semanas cumplidas se considera a término. Por eso conviene tener la bolsa del hospital lista hacia la semana 36.' },
    ],
    faq: [
      { q: '¿Desde cuándo se cuentan las semanas de embarazo?', a: 'Desde el primer día de la última regla. Por eso, en el momento de la concepción ya estás aproximadamente en la semana 3 de embarazo.' },
      { q: '¿Qué significa 24+3?', a: '24 semanas completas y 3 días. Estás entonces en la semana 25 de embarazo.' },
      { q: '¿Cuánto dura cada trimestre?', a: 'El primero hasta el final de la semana 13 (13+6), el segundo hasta el final de la semana 27 (27+6) y el tercero desde la semana 28 hasta el parto.' },
    ],
    sources: [
      'ACOG Committee Opinion No. 700: Methods for Estimating the Due Date (2017)',
      'OMS: Nacimientos prematuros, definiciones de parto prematuro y a término (2023)',
    ],
    related: ['bag', 'labor'],
  },
}

const bag = {
  pl: {
    id: 'bag',
    published: '2026-10-03',
    slug: 'torba-do-szpitala-lista',
    emoji: '🧳',
    title: 'Torba do szpitala: lista rzeczy do porodu',
    metaTitle: 'Torba do szpitala do porodu: lista dla mamy i dziecka',
    description: 'Co spakować do szpitala na poród: dokumenty, rzeczy dla mamy, dla noworodka i dla osoby towarzyszącej. Lista do odhaczenia, najlepiej spakowana około 36. tygodnia.',
    teaser: 'Dokumenty, rzeczy dla mamy i dziecka.',
    basedOn: 'NHS, standard opieki okołoporodowej',
    answer: 'Torbę spakuj około 36. tygodnia ciąży. Najważniejsze są dokumenty (dowód osobisty, karta przebiegu ciąży i wyniki badań), rzeczy dla Ciebie na 2 do 3 dni i ubranko dla dziecka na wyjście. Każdy szpital ma swoją listę, więc sprawdź ją na stronie porodówki.',
    blocks: [
      { h2: 'Dokumenty' },
      { ul: [
        'Dowód osobisty',
        'Karta przebiegu ciąży i wyniki badań, w tym grupa krwi i wynik posiewu w kierunku paciorkowca GBS',
        'Opisy USG',
        'Plan porodu, jeśli go przygotowałaś',
        'Skierowanie do szpitala, jeśli lekarz je wystawił',
      ] },
      { h2: 'Dla mamy' },
      { ul: [
        '2 do 3 koszul nocnych rozpinanych z przodu, wygodnych do karmienia',
        'Szlafrok, kapcie i klapki pod prysznic',
        'Majtki poporodowe (jednorazowe albo siateczkowe) i duże podpaski poporodowe',
        'Biustonosz do karmienia i wkładki laktacyjne',
        'Kosmetyki, ręcznik, gumka do włosów',
        'Woda niegazowana i lekkie przekąski',
        'Ładowarka do telefonu z długim kablem',
        'Luźne ubranie na wyjście: brzuch po porodzie nie znika od razu',
      ] },
      { h2: 'Dla dziecka' },
      { ul: [
        '2 do 3 kompletów: body i pajacyki w rozmiarze 56',
        'Czapeczka i skarpetki',
        'Pieluszki w rozmiarze 1 i chusteczki, jeśli szpital ich nie zapewnia',
        'Kocyk albo rożek',
        'Ubranko na wyjście dopasowane do pogody',
        'Fotelik samochodowy: zostaje w aucie do dnia wyjścia',
      ] },
      { h2: 'Dla osoby towarzyszącej' },
      { ul: [
        'Wygodne ubranie i obuwie na zmianę',
        'Woda i przekąski',
        'Karta albo drobne na parking i automaty',
        'Ładowarka',
      ] },
      { callout: { title: 'Kiedy spakować torbę?', text: 'Najlepiej około 36. tygodnia. Ciąża jest donoszona od 37. tygodnia, a poród może zacząć się wcześniej, niż się spodziewasz. Kiedy jechać do szpitala, przeczytasz w artykule <a href="/poradnik/kiedy-jechac-do-szpitala-na-porod/">kiedy jechać na porodówkę</a>.' } },
    ],
    sources: [
      'NHS: Pack your bag for labour (nhs.uk)',
      'Rozporządzenie Ministra Zdrowia z 16 sierpnia 2018 r. w sprawie standardu organizacyjnego opieki okołoporodowej (badania w ciąży)',
    ],
    app: 'W trybie ciąży aplikacja liczy tydzień i dni do terminu, a gdy zacznie się poród, zmierzysz skurcze jednym przyciskiem.',
    related: ['labor'],
    tool: 'dueDate',
  },
  en: {
    id: 'bag',
    published: '2026-10-03',
    slug: 'hospital-bag-checklist',
    emoji: '🧳',
    title: 'Hospital bag checklist for labour',
    metaTitle: 'Hospital bag checklist: what to pack for you and your baby',
    description: 'What to pack in your hospital bag for labour: documents, things for you, your newborn and your birth partner. A checklist to pack by about 36 weeks.',
    teaser: 'Documents, things for you and your baby.',
    basedOn: 'NHS',
    answer: 'Pack your hospital bag by about 36 weeks. The essentials are your maternity notes, things for you for 2 to 3 days and an outfit for your baby to go home in. Every hospital has its own list, so check your maternity unit’s website.',
    blocks: [
      { h2: 'Documents' },
      { ul: [
        'Your maternity notes (paper notes or the app your maternity service uses)',
        'Test results and scan reports, including your blood group',
        'Your birth plan, if you have one',
        'Photo ID and insurance details, if your hospital asks for them',
      ] },
      { h2: 'For you' },
      { ul: [
        '2 or 3 front-opening nightdresses or big T-shirts that are easy to breastfeed in',
        'A dressing gown, slippers and flip-flops for the shower',
        'Comfortable maternity pads and disposable or loose cotton underwear',
        'A nursing bra and breast pads',
        'Toiletries, a towel and a hair tie',
        'Water and light snacks',
        'A phone charger with a long cable',
        'Loose clothes to go home in: your bump doesn’t disappear straight away',
      ] },
      { h2: 'For your baby' },
      { ul: [
        '2 or 3 sets of bodysuits and sleepsuits in newborn size',
        'A hat and socks',
        'Newborn nappies and wipes, if the hospital doesn’t provide them',
        'A blanket',
        'An outfit to go home in, suitable for the weather',
        'A rear-facing car seat: leave it in the car until you go home',
      ] },
      { h2: 'For your birth partner' },
      { ul: [
        'A change of comfortable clothes and shoes',
        'Water and snacks',
        'A card or change for parking and vending machines',
        'A charger',
      ] },
      { callout: { title: 'When should I pack?', text: 'By about 36 weeks. A pregnancy is full term from 37 weeks, and labour can start earlier than you expect. When to go in: <a href="/en/guide/when-to-go-to-hospital-in-labour/">when to go to the hospital in labour</a>.' } },
    ],
    sources: [
      'NHS: Pack your bag for labour (nhs.uk)',
    ],
    app: 'In pregnancy mode the app counts your week and the days to your due date, and when labour starts you can time contractions with one button.',
    related: ['labor'],
    tool: 'dueDate',
  },
  de: {
    id: 'bag',
    published: '2026-10-03',
    slug: 'kliniktasche-checkliste',
    emoji: '🧳',
    title: 'Kliniktasche für die Geburt: Checkliste',
    metaTitle: 'Kliniktasche packen: Checkliste für Mama und Baby',
    description: 'Was in die Kliniktasche zur Geburt gehört: Dokumente, Sachen für Sie, Ihr Neugeborenes und die Begleitperson. Eine Checkliste, am besten bis zur 36. SSW gepackt.',
    teaser: 'Dokumente, Sachen für Mama und Baby.',
    basedOn: 'NHS, Mutterschafts-Richtlinien',
    answer: 'Packen Sie die Kliniktasche bis etwa zur 36. SSW. Am wichtigsten sind die Dokumente (Mutterpass, Versichertenkarte, Personalausweis), Sachen für Sie für 2 bis 3 Tage und ein Outfit für das Baby für den Heimweg. Jede Klinik hat eine eigene Liste, schauen Sie auf der Website Ihrer Geburtsklinik nach.',
    blocks: [
      { h2: 'Dokumente' },
      { ul: [
        'Mutterpass',
        'Versichertenkarte der Krankenkasse',
        'Personalausweis',
        'Für die Geburtsanzeige: Heiratsurkunde oder Ihre Geburtsurkunden, bei Unverheirateten die Vaterschaftsanerkennung, falls vorhanden',
        'Geburtsplan, wenn Sie einen haben',
      ] },
      { h2: 'Für Sie' },
      { ul: [
        '2 bis 3 vorne zu öffnende Nachthemden, bequem zum Stillen',
        'Bademantel, Hausschuhe und Badeschlappen',
        'Wochenbett-Unterhosen (Einweg oder Netzslips) und große Wochenbettbinden',
        'Still-BH und Stilleinlagen',
        'Kosmetik, Handtuch, Haargummi',
        'Stilles Wasser und leichte Snacks',
        'Handy-Ladekabel, möglichst lang',
        'Lockere Kleidung für den Heimweg: Der Bauch verschwindet nicht sofort',
      ] },
      { h2: 'Für das Baby' },
      { ul: [
        '2 bis 3 Garnituren: Bodys und Strampler in Größe 50 oder 56',
        'Mützchen und Söckchen',
        'Windeln für Neugeborene und Feuchttücher, falls die Klinik keine stellt',
        'Decke',
        'Ein Outfit für den Heimweg, passend zum Wetter',
        'Babyschale fürs Auto: bleibt bis zur Entlassung im Auto',
      ] },
      { h2: 'Für die Begleitperson' },
      { ul: [
        'Bequeme Kleidung und Schuhe zum Wechseln',
        'Wasser und Snacks',
        'Karte oder Kleingeld für Parkplatz und Automaten',
        'Ladegerät',
      ] },
      { callout: { title: 'Wann packen?', text: 'Am besten bis etwa zur 36. SSW. Ab 37 Wochen ist das Kind reif, und die Geburt kann früher beginnen als gedacht. Wann Sie losfahren sollten: <a href="/de/ratgeber/wann-in-die-klinik-zur-geburt/">wann in die Klinik zur Geburt</a>.' } },
    ],
    sources: [
      'NHS: Pack your bag for labour (nhs.uk)',
      'Gemeinsamer Bundesausschuss: Mutterschafts-Richtlinien (Mutterpass)',
    ],
    app: 'Im Schwangerschaftsmodus zählt die App die SSW und die Tage bis zum Termin, und wenn die Geburt beginnt, messen Sie die Wehen mit einem Knopf.',
    related: ['labor'],
    tool: 'dueDate',
  },
  fr: {
    id: 'bag',
    published: '2026-10-03',
    slug: 'valise-maternite-liste',
    emoji: '🧳',
    title: 'Valise de maternité : la liste complète',
    metaTitle: 'Valise de maternité : liste pour maman et bébé',
    description: 'Que mettre dans la valise de maternité : papiers, affaires pour vous, pour le nouveau-né et pour l’accompagnant. Une liste à préparer vers 36 SA.',
    teaser: 'Papiers, affaires pour maman et bébé.',
    basedOn: 'NHS, Assurance Maladie',
    answer: 'Préparez la valise de maternité vers 36 SA. L’essentiel : les papiers (pièce d’identité, carte Vitale, dossier de grossesse), vos affaires pour 2 à 3 jours et une tenue de sortie pour bébé. Chaque maternité a sa propre liste, vérifiez celle de la vôtre.',
    blocks: [
      { h2: 'Papiers' },
      { ul: [
        'Pièce d’identité',
        'Carte Vitale et carte de mutuelle',
        'Dossier de grossesse : résultats d’examens, comptes rendus d’échographie, carte de groupe sanguin',
        'Livret de famille, ou reconnaissance anticipée si vous n’êtes pas mariés',
        'Projet de naissance, si vous en avez un',
      ] },
      { h2: 'Pour vous' },
      { ul: [
        '2 ou 3 chemises de nuit qui s’ouvrent devant, pratiques pour allaiter',
        'Peignoir, chaussons et tongs pour la douche',
        'Culottes jetables ou en filet et serviettes de maternité',
        'Soutien-gorge d’allaitement et coussinets',
        'Trousse de toilette, serviette, élastique pour les cheveux',
        'Eau plate et en-cas légers',
        'Chargeur de téléphone avec un long câble',
        'Vêtements amples pour la sortie : le ventre ne disparaît pas tout de suite',
      ] },
      { h2: 'Pour bébé' },
      { ul: [
        '2 ou 3 tenues : bodies et pyjamas taille naissance',
        'Bonnet et chaussettes',
        'Couches nouveau-né et lingettes, si la maternité n’en fournit pas',
        'Gigoteuse ou couverture',
        'Tenue de sortie adaptée à la météo',
        'Siège auto dos à la route : il reste dans la voiture jusqu’à la sortie',
      ] },
      { h2: 'Pour l’accompagnant' },
      { ul: [
        'Vêtements et chaussures confortables de rechange',
        'Eau et en-cas',
        'Carte ou monnaie pour le parking et les distributeurs',
        'Chargeur',
      ] },
      { callout: { title: 'Quand préparer la valise ?', text: 'Vers 36 SA. La grossesse est à terme dès 37 SA, et le travail peut commencer plus tôt que prévu. Quand partir : <a href="/fr/guide/quand-partir-a-la-maternite/">quand partir à la maternité</a>.' } },
    ],
    sources: [
      'NHS : Pack your bag for labour (nhs.uk)',
      'Assurance Maladie (ameli.fr) : déclarer et préparer la naissance',
    ],
    app: 'En mode grossesse, l’appli compte les SA et les jours avant le terme, et quand le travail commence, vous chronométrez les contractions d’un seul bouton.',
    related: ['labor'],
    tool: 'dueDate',
  },
  es: {
    id: 'bag',
    published: '2026-10-03',
    slug: 'bolsa-del-hospital-lista',
    emoji: '🧳',
    title: 'Bolsa del hospital para el parto: lista completa',
    metaTitle: 'Bolsa del hospital para el parto: lista para mamá y bebé',
    description: 'Qué llevar en la bolsa del hospital para el parto: documentos, cosas para ti, para el recién nacido y para tu acompañante. Una lista para tenerla lista hacia la semana 36.',
    teaser: 'Documentos, cosas para mamá y bebé.',
    basedOn: 'NHS',
    answer: 'Prepara la bolsa del hospital hacia la semana 36. Lo más importante son los documentos (DNI, tarjeta sanitaria y cartilla del embarazo), tus cosas para 2 o 3 días y la ropa de salida del bebé. Cada hospital tiene su propia lista, revisa la de tu maternidad.',
    blocks: [
      { h2: 'Documentos' },
      { ul: [
        'DNI o pasaporte',
        'Tarjeta sanitaria',
        'Cartilla del embarazo con analíticas e informes de las ecografías',
        'Libro de familia, si lo tienes (en muchos hospitales se inscribe al bebé allí mismo)',
        'Plan de parto, si lo has preparado',
      ] },
      { h2: 'Para ti' },
      { ul: [
        '2 o 3 camisones que se abran por delante, cómodos para dar el pecho',
        'Bata, zapatillas y chanclas para la ducha',
        'Braguitas desechables o de malla y compresas tocológicas',
        'Sujetador de lactancia y discos de lactancia',
        'Neceser, toalla y goma para el pelo',
        'Agua y tentempiés ligeros',
        'Cargador del móvil con cable largo',
        'Ropa holgada para la salida: la barriga no desaparece enseguida',
      ] },
      { h2: 'Para el bebé' },
      { ul: [
        '2 o 3 mudas: bodies y pijamas de talla recién nacido',
        'Gorrito y calcetines',
        'Pañales de recién nacido y toallitas, si el hospital no los da',
        'Mantita o arrullo',
        'Ropa de salida adecuada al tiempo',
        'Silla de coche a contramarcha: se queda en el coche hasta el alta',
      ] },
      { h2: 'Para tu acompañante' },
      { ul: [
        'Ropa y calzado cómodos de recambio',
        'Agua y tentempiés',
        'Tarjeta o monedas para el parking y las máquinas',
        'Cargador',
      ] },
      { callout: { title: '¿Cuándo preparar la bolsa?', text: 'Hacia la semana 36. El embarazo es a término desde la semana 37 y el parto puede empezar antes de lo esperado. Cuándo ir: <a href="/es/guia/cuando-ir-al-hospital-de-parto/">cuándo ir al hospital de parto</a>.' } },
    ],
    sources: [
      'NHS: Pack your bag for labour (nhs.uk)',
    ],
    app: 'En el modo embarazo la app cuenta la semana y los días hasta la fecha prevista, y cuando empiece el parto mides las contracciones con un solo botón.',
    related: ['labor'],
    tool: 'dueDate',
  },
}

const labor = {
  pl: {
    id: 'labor',
    published: '2026-10-03',
    slug: 'kiedy-jechac-do-szpitala-na-porod',
    emoji: '🏥',
    title: 'Kiedy jechać do szpitala na poród?',
    metaTitle: 'Kiedy jechać na porodówkę? Skurcze, wody i objawy alarmowe',
    description: 'Kiedy jechać do szpitala na poród: regularne skurcze, odejście wód i objawy, przy których nie czekasz. Na podstawie zaleceń NHS i ACOG.',
    teaser: 'Skurcze, wody i objawy, z którymi nie czekasz.',
    basedOn: 'NHS, ACOG',
    answer: 'Do szpitala jedziesz, gdy skurcze są regularne, coraz silniejsze i coraz częstsze. Często mówi się o skurczach co około 5 minut przez godzinę, ale zapytaj swoją położną albo szpital, czego trzymać się u Ciebie. Od razu dzwoń albo jedź, gdy odejdą wody, pojawi się krwawienie, dziecko rusza się słabiej niż zwykle albo skurcze zaczną się przed 37. tygodniem.',
    blocks: [
      { h2: 'Skurcze przepowiadające czy porodowe?' },
      { table: {
        head: ['Cecha', 'Przepowiadające', 'Porodowe'],
        rows: [
          ['Odstępy', 'nieregularne', 'regularne i coraz krótsze'],
          ['Siła', 'nie narastają', 'coraz silniejsze i dłuższe'],
          ['Po zmianie pozycji albo ciepłym prysznicu', 'często słabną', 'nie mijają'],
          ['Ból', 'zwykle z przodu brzucha', 'często od pleców do przodu'],
        ],
      } },
      { h2: 'Kiedy jechać przy skurczach' },
      { p: 'Szpitale podają różne progi. W wielu krajach mówi się o skurczach co około 5 minut, trwających około minuty, przez godzinę (zasada 5-1-1). Brytyjska NHS zaleca kontakt z porodówką, gdy masz mniej więcej 3 skurcze w ciągu 10 minut. Przy kolejnym porodzie zwykle wszystko idzie szybciej, więc warto ruszyć wcześniej, zwłaszcza gdy szpital jest daleko.' },
      { h2: 'Jedź od razu albo dzwoń po pomoc, gdy' },
      { ul: [
        'odejdą wody, zwłaszcza zielone, brązowe albo o nieprzyjemnym zapachu',
        'pojawi się krwawienie z pochwy',
        'dziecko rusza się słabiej albo rzadziej niż zwykle',
        'skurcze zaczną się przed 37. tygodniem ciąży',
        'masz silny, stały ból brzucha, który nie mija między skurczami',
        'masz gorączkę, silny ból głowy, zaburzenia widzenia albo nagły obrzęk twarzy i rąk',
      ] },
      { callout: { title: 'Wody odeszły, a skurczy brak', text: 'Zadzwoń do szpitala nawet bez skurczy. Zapisz godzinę i kolor wód, użyj podpaski, nie tamponu. Szpital powie Ci, czy przyjechać od razu. Spakowana torba ułatwia sprawę: <a href="/poradnik/torba-do-szpitala-lista/">lista rzeczy do szpitala</a>.' } },
    ],
    sources: [
      'NHS: Signs that labour has begun (nhs.uk)',
      'NHS: What happens if your waters break early (nhs.uk)',
      'ACOG: How to Tell When Labor Begins (acog.org)',
    ],
    app: 'Licznik skurczy w aplikacji mierzy czas trwania i odstępy jednym przyciskiem, a ekran nie gaśnie, gdy liczysz.',
    related: ['bag'],
    tool: 'dueDate',
  },
  en: {
    id: 'labor',
    published: '2026-10-03',
    slug: 'when-to-go-to-hospital-in-labour',
    emoji: '🏥',
    title: 'When to go to the hospital in labour',
    metaTitle: 'When to go to hospital in labour: contractions, waters, warning signs',
    description: 'When to go to the hospital in labour: regular contractions, your waters breaking and the warning signs that mean don’t wait. Based on NHS and ACOG advice.',
    teaser: 'Contractions, waters and signs not to wait.',
    basedOn: 'NHS, ACOG',
    answer: 'Go in when your contractions are regular, getting stronger and closer together. A common rule is contractions about every 5 minutes for an hour, but ask your midwife or hospital what they want you to do. Call or go straight away if your waters break, you bleed, your baby moves less than usual or contractions start before 37 weeks.',
    blocks: [
      { h2: 'False labour or real labour?' },
      { table: {
        head: ['Feature', 'False labour', 'Real labour'],
        rows: [
          ['Timing', 'irregular', 'regular and closer together'],
          ['Strength', 'doesn’t build up', 'stronger and longer'],
          ['After moving or a warm shower', 'often eases', 'doesn’t stop'],
          ['Pain', 'usually at the front', 'often from the back to the front'],
        ],
      } },
      { h2: 'When to go in with contractions' },
      { p: 'Hospitals use different thresholds. In the US, a common rule is contractions about every 5 minutes, lasting about a minute, for an hour (5-1-1). The NHS advises contacting your maternity unit when you have about 3 contractions every 10 minutes. Second and later labours are often faster, so leave earlier, especially if the hospital is far away.' },
      { h2: 'Call or go straight away if' },
      { ul: [
        'your waters break, especially if they are green, brown or smell unpleasant',
        'you have vaginal bleeding',
        'your baby is moving less or less often than usual',
        'contractions start before 37 weeks',
        'you have strong, constant tummy pain that doesn’t ease between contractions',
        'you have a fever, a severe headache, problems with your vision or sudden swelling of your face and hands',
      ] },
      { callout: { title: 'Waters broken but no contractions', text: 'Call the hospital even without contractions. Note the time and colour of the waters and use a pad, not a tampon. The hospital will tell you whether to come in now. A packed bag helps: <a href="/en/guide/hospital-bag-checklist/">hospital bag checklist</a>.' } },
    ],
    sources: [
      'NHS: Signs that labour has begun (nhs.uk)',
      'NHS: What happens if your waters break early (nhs.uk)',
      'ACOG: How to Tell When Labor Begins (acog.org)',
    ],
    app: 'The contraction timer in the app measures duration and intervals with one button, and the screen stays on while you time.',
    related: ['bag'],
    tool: 'dueDate',
  },
  de: {
    id: 'labor',
    published: '2026-10-03',
    slug: 'wann-in-die-klinik-zur-geburt',
    emoji: '🏥',
    title: 'Wann in die Klinik zur Geburt?',
    metaTitle: 'Wann in die Klinik zur Geburt? Wehen, Blasensprung, Warnzeichen',
    description: 'Wann Sie zur Geburt in die Klinik fahren: regelmäßige Wehen, Blasensprung und Warnzeichen, bei denen Sie nicht warten. Nach Empfehlungen von NHS und ACOG.',
    teaser: 'Wehen, Blasensprung und Warnzeichen.',
    basedOn: 'NHS, ACOG',
    answer: 'Fahren Sie los, wenn die Wehen regelmäßig, stärker und häufiger werden. Oft heißt es: etwa alle 5 Minuten über eine Stunde. Fragen Sie aber Ihre Hebamme oder Klinik, was für Sie gilt. Sofort anrufen oder losfahren sollten Sie bei Blasensprung, Blutungen, weniger Kindsbewegungen als sonst oder Wehen vor der 37. SSW.',
    blocks: [
      { h2: 'Übungswehen oder Geburtswehen?' },
      { table: {
        head: ['Merkmal', 'Übungs- und Senkwehen', 'Geburtswehen'],
        rows: [
          ['Abstände', 'unregelmäßig', 'regelmäßig und kürzer werdend'],
          ['Stärke', 'nehmen nicht zu', 'stärker und länger'],
          ['Nach Bewegung oder warmer Dusche', 'lassen oft nach', 'hören nicht auf'],
          ['Schmerz', 'meist vorne am Bauch', 'oft vom Rücken nach vorne'],
        ],
      } },
      { h2: 'Wann bei Wehen losfahren' },
      { p: 'Kliniken nennen unterschiedliche Richtwerte. Viele empfehlen beim ersten Kind, zu kommen, wenn die Wehen etwa eine Stunde lang regelmäßig alle 5 Minuten kommen und rund eine Minute dauern. Der britische NHS rät, sich zu melden, wenn etwa 3 Wehen in 10 Minuten kommen. Beim zweiten Kind geht es oft schneller, fahren Sie also früher los, vor allem bei weitem Weg.' },
      { h2: 'Sofort anrufen oder losfahren, wenn' },
      { ul: [
        'die Fruchtblase platzt, besonders bei grünem, braunem oder übel riechendem Fruchtwasser',
        'Blutungen aus der Scheide auftreten',
        'sich Ihr Baby weniger oder seltener bewegt als sonst',
        'Wehen vor der 37. SSW beginnen',
        'Sie starke, anhaltende Bauchschmerzen haben, die zwischen den Wehen nicht nachlassen',
        'Sie Fieber, starke Kopfschmerzen, Sehstörungen oder plötzliche Schwellungen an Gesicht und Händen haben',
      ] },
      { callout: { title: 'Blasensprung ohne Wehen', text: 'Rufen Sie auch ohne Wehen in der Klinik an. Notieren Sie Uhrzeit und Farbe des Fruchtwassers und nehmen Sie eine Binde, keinen Tampon. Die Klinik sagt Ihnen, ob Sie sofort kommen sollen. Eine gepackte Tasche hilft: <a href="/de/ratgeber/kliniktasche-checkliste/">Kliniktasche: Checkliste</a>.' } },
    ],
    sources: [
      'NHS: Signs that labour has begun (nhs.uk)',
      'NHS: What happens if your waters break early (nhs.uk)',
      'ACOG: How to Tell When Labor Begins (acog.org)',
    ],
    app: 'Der Wehen-Timer der App misst Dauer und Abstände mit einem Knopf, und der Bildschirm bleibt beim Messen an.',
    related: ['bag'],
    tool: 'dueDate',
  },
  fr: {
    id: 'labor',
    published: '2026-10-03',
    slug: 'quand-partir-a-la-maternite',
    emoji: '🏥',
    title: 'Quand partir à la maternité ?',
    metaTitle: 'Quand partir à la maternité ? Contractions, perte des eaux, signes d’alerte',
    description: 'Quand partir à la maternité : contractions régulières, perte des eaux et signes qui imposent de partir tout de suite. D’après le NHS, l’ACOG et les conseils courants des maternités françaises.',
    teaser: 'Contractions, perte des eaux et signes d’alerte.',
    basedOn: 'NHS, ACOG',
    answer: 'Partez quand les contractions deviennent régulières, plus fortes et plus rapprochées. En France, beaucoup de maternités conseillent de partir quand elles reviennent toutes les 5 minutes depuis environ 2 heures pour un premier bébé, et environ 1 heure pour les suivants : demandez la règle de votre maternité. Appelez ou partez tout de suite en cas de perte des eaux, de saignement, si bébé bouge moins que d’habitude ou si les contractions commencent avant 37 SA.',
    blocks: [
      { h2: 'Contractions de « faux travail » ou de travail ?' },
      { table: {
        head: ['Signe', 'Faux travail', 'Vrai travail'],
        rows: [
          ['Rythme', 'irrégulier', 'régulier et de plus en plus rapproché'],
          ['Intensité', 'n’augmente pas', 'de plus en plus fortes et longues'],
          ['Après un changement de position ou une douche chaude', 'diminuent souvent', 'ne s’arrêtent pas'],
          ['Douleur', 'surtout à l’avant du ventre', 'souvent du dos vers l’avant'],
        ],
      } },
      { h2: 'Quand partir avec les contractions' },
      { p: 'Les seuils varient selon les maternités. Pour un premier bébé, on conseille souvent de partir quand les contractions reviennent toutes les 5 minutes depuis environ 2 heures. Aux États-Unis, on parle de contractions toutes les 5 minutes, d’environ une minute, pendant une heure. Pour un deuxième bébé, le travail est souvent plus rapide : partez plus tôt, surtout si la maternité est loin.' },
      { h2: 'Appelez ou partez tout de suite si' },
      { ul: [
        'vous perdez les eaux, surtout si le liquide est vert, marron ou malodorant',
        'vous saignez',
        'bébé bouge moins ou moins souvent que d’habitude',
        'les contractions commencent avant 37 SA',
        'vous avez une douleur au ventre forte et continue, sans répit entre les contractions',
        'vous avez de la fièvre, un mal de tête violent, des troubles de la vue ou un gonflement soudain du visage et des mains',
      ] },
      { callout: { title: 'Perte des eaux sans contractions', text: 'Appelez la maternité même sans contractions. Notez l’heure et la couleur du liquide et utilisez une serviette, pas de tampon. La maternité vous dira si vous devez venir tout de suite. Une valise prête simplifie tout : <a href="/fr/guide/valise-maternite-liste/">valise de maternité : la liste</a>.' } },
    ],
    sources: [
      'NHS : Signs that labour has begun (nhs.uk)',
      'NHS : What happens if your waters break early (nhs.uk)',
      'ACOG : How to Tell When Labor Begins (acog.org)',
    ],
    app: 'Le minuteur de contractions de l’appli mesure la durée et l’intervalle d’un seul bouton, et l’écran reste allumé pendant le chronométrage.',
    related: ['bag'],
    tool: 'dueDate',
  },
  es: {
    id: 'labor',
    published: '2026-10-03',
    slug: 'cuando-ir-al-hospital-de-parto',
    emoji: '🏥',
    title: '¿Cuándo ir al hospital de parto?',
    metaTitle: '¿Cuándo ir al hospital de parto? Contracciones, romper aguas y señales de alarma',
    description: 'Cuándo ir al hospital de parto: contracciones regulares, romper aguas y las señales con las que no hay que esperar. Según las recomendaciones del NHS y la ACOG.',
    teaser: 'Contracciones, romper aguas y señales de alarma.',
    basedOn: 'NHS, ACOG',
    answer: 'Ve al hospital cuando las contracciones sean regulares, cada vez más fuertes y más seguidas. Muchos hospitales aconsejan ir cuando llegan cada 5 minutos durante al menos una hora, pero pregunta a tu matrona o a tu hospital qué debes hacer. Llama o ve enseguida si rompes aguas, sangras, tu bebé se mueve menos de lo habitual o las contracciones empiezan antes de la semana 37.',
    blocks: [
      { h2: '¿Contracciones de preparto o de parto?' },
      { table: {
        head: ['Rasgo', 'Preparto', 'Parto'],
        rows: [
          ['Ritmo', 'irregulares', 'regulares y cada vez más seguidas'],
          ['Intensidad', 'no aumentan', 'cada vez más fuertes y largas'],
          ['Al cambiar de postura o con una ducha caliente', 'suelen calmarse', 'no se detienen'],
          ['Dolor', 'sobre todo en la parte delantera', 'a menudo de la espalda hacia delante'],
        ],
      } },
      { h2: 'Cuándo ir con contracciones' },
      { p: 'Cada hospital usa sus propios umbrales. Una regla habitual es ir con contracciones cada unos 5 minutos, de alrededor de un minuto, durante una hora (5-1-1). El NHS británico aconseja llamar cuando tienes unas 3 contracciones cada 10 minutos. En el segundo parto todo suele ir más rápido, así que sal antes, sobre todo si el hospital está lejos.' },
      { h2: 'Llama o ve enseguida si' },
      { ul: [
        'rompes aguas, sobre todo si el líquido es verde, marrón o huele mal',
        'tienes sangrado vaginal',
        'tu bebé se mueve menos o con menos frecuencia de lo habitual',
        'las contracciones empiezan antes de la semana 37',
        'tienes un dolor de barriga fuerte y continuo que no cede entre contracciones',
        'tienes fiebre, un dolor de cabeza intenso, problemas de visión o hinchazón repentina de la cara y las manos',
      ] },
      { callout: { title: 'Has roto aguas pero no hay contracciones', text: 'Llama al hospital aunque no tengas contracciones. Apunta la hora y el color del líquido y usa una compresa, no un tampón. En el hospital te dirán si debes ir ya. Tener la bolsa lista ayuda: <a href="/es/guia/bolsa-del-hospital-lista/">bolsa del hospital: lista</a>.' } },
    ],
    sources: [
      'NHS: Signs that labour has begun (nhs.uk)',
      'NHS: What happens if your waters break early (nhs.uk)',
      'ACOG: How to Tell When Labor Begins (acog.org)',
    ],
    app: 'El contador de contracciones de la app mide la duración y los intervalos con un solo botón, y la pantalla no se apaga mientras cuentas.',
    related: ['bag'],
    tool: 'dueDate',
  },
}

// Tylko PL: harmonogram według polskiego standardu opieki okołoporodowej.
const exams = {
  id: 'exams',
  onlyLangs: ['pl'],
  published: '2026-10-03',
  slug: 'badania-w-ciazy-harmonogram',
  emoji: '🩺',
  title: 'Badania w ciąży: harmonogram tydzień po tygodniu',
  metaTitle: 'Badania w ciąży 2026: harmonogram według tygodni ciąży',
  description: 'Jakie badania w którym tygodniu ciąży według standardu opieki okołoporodowej, stan na 2026 rok. Lista do wydruku i plik do kalendarza z przypomnieniami.',
  teaser: 'Co i kiedy zrobić, plus plik do kalendarza.',
  basedOn: 'standard opieki okołoporodowej (Dz.U. 2026 poz. 1140)',
  answer: 'W ciąży o prawidłowym przebiegu wizyta jest nie rzadziej niż co 4 tygodnie. Najwięcej badań robi się do 10. tygodnia, USG w 11. do 14., 18. do 22. i 27. do 32. tygodniu, test obciążenia glukozą w 24. do 28. tygodniu, a posiew w kierunku GBS w 35. do 37. tygodniu. Wpisz termin porodu poniżej, a pobierzesz cały harmonogram do kalendarza.',
  blocks: [
    { ics: {
      title: 'Harmonogram w Twoim kalendarzu',
      label: 'Termin porodu',
      button: 'Pobierz plik do kalendarza (.ics)',
      note: 'Plik otworzysz w Kalendarzu Google, Apple albo Outlook. Każde badanie ma przypomnienie dzień wcześniej. Data zostaje w Twojej przeglądarce, nigdzie jej nie wysyłamy.',
      noDue: 'Nie znasz terminu? <a href="/poradnik/kalkulator-terminu-porodu/">Policz termin porodu</a>.',
      error: 'Wybierz termin porodu z najbliższych 40 tygodni.',
      done: 'Gotowe: plik z badaniami jest w pobranych.',
      eventPrefix: 'Badania w ciąży',
      fileName: 'badania-w-ciazy.ics',
    } },
    { h2: 'Harmonogram badań' },
    { schedule: true },
    { callout: { title: 'Badania prenatalne', text: 'Badania prenatalne finansowane przez NFZ, na przykład test PAPP-A razem z USG w 11. do 14. tygodniu, omów z lekarzem na pierwszej wizycie, żeby zdążyć w terminie.' } },
    { h2: 'Wizyty co 4 tygodnie' },
    { p: 'Lekarz albo położna na każdej wizycie mierzy ciśnienie i masę ciała i ocenia przebieg ciąży. Od 21. tygodnia ocenia też czynność serca dziecka, a od 33. tygodnia ruchy dziecka. Gdy coś odbiega od normy, lekarz może zlecić więcej badań albo częstsze wizyty.' },
  ],
  sources: [
    'Obwieszczenie Ministra Zdrowia z 18 sierpnia 2026 r. w sprawie ogłoszenia jednolitego tekstu rozporządzenia w sprawie standardu organizacyjnego opieki okołoporodowej (Dz.U. 2026 poz. 1140)',
    'Rozporządzenie Ministra Zdrowia z 23 października 2025 r. zmieniające rozporządzenie w sprawie standardu organizacyjnego opieki okołoporodowej (Dz.U. 2025 poz. 1525)',
  ],
  app: 'W trybie ciąży aplikacja liczy tydzień i dni do terminu i ma licznik skurczy. Lista badań z przypomnieniami jest w przygotowaniu.',
  related: ['bag', 'labor'],
  tool: 'dueDate',
}

const ui = {
  pl: {
    tools: 'Narzędzia', pregnancy: 'Ciąża', baby: 'Niemowlę', toolCta: 'Policz termin porodu', faq: 'Najczęstsze pytania',
    sheet: {
      title: 'Ściągawka ciążowa na lodówkę (PDF)',
      text: 'Badania według tygodni, objawy, z którymi jedziesz do szpitala od razu, torba i miejsce na telefony. Jedna strona A4 do wydruku.',
      link: 'Pobierz ściągawkę ciążową',
      href: '/assets/sr/pl/sciagawka-ciaza.pdf',
    },
  },
  en: { tools: 'Tools', pregnancy: 'Pregnancy', baby: 'Baby', toolCta: 'Calculate your due date', faq: 'Frequently asked questions' },
  de: { tools: 'Rechner', pregnancy: 'Schwangerschaft', baby: 'Baby', toolCta: 'Geburtstermin berechnen', faq: 'Häufige Fragen' },
  fr: { tools: 'Outils', pregnancy: 'Grossesse', baby: 'Bébé', toolCta: 'Calculer la date d’accouchement', faq: 'Questions fréquentes' },
  es: { tools: 'Herramientas', pregnancy: 'Embarazo', baby: 'Bebé', toolCta: 'Calcular la fecha de parto', faq: 'Preguntas frecuentes' },
}

const LANGS = ['pl', 'en', 'de', 'fr', 'es']
export default Object.fromEntries(LANGS.map(l => [l, {
  ui: ui[l],
  tools: [dueDate[l]],
  articles: [...(l === 'pl' ? [exams] : []), bag[l], labor[l]].map(a => ({ ...a, section: 'pregnancy' })),
}]))
